export const openSourceLearningContent = [
  {
    id: "codex-plugin-claude-code-readme-translation",
    sourceUrl: "https://github.com/openai/codex-plugin-cc",
    translationMode: "fullTranslation",
    title: "Codex for Claude Code 插件：在 Claude Code 里调用 Codex 做审查和任务委派",
    originalTitle: "Codex plugin for Claude Code",
    notice: "",
    showSourceAddress: true,
    hideSourceNoticeLink: true,
    hideArticleSiteLink: true,
    hideLead: true,
    sections: [
      {
        heading: "Codex for Claude Code 插件",
        blocks: [
          {
            type: "paragraph",
            content: "在 Claude Code 里面使用 Codex 做代码审查，或者把任务委派给 Codex。",
          },
          {
            type: "paragraph",
            content: "这个插件面向 Claude Code 用户：如果你已经有自己的 Claude Code 工作流，但想用一种简单方式开始使用 Codex，它就适合你。",
          },
        ],
      },
      {
        heading: "你会得到什么",
        blocks: [
          { type: "paragraph", content: "/codex:review：普通的只读 Codex 审查。" },
          { type: "paragraph", content: "/codex:adversarial-review：可以指定方向的挑战式审查。" },
          { type: "paragraph", content: "/codex:rescue、/codex:status、/codex:result 和 /codex:cancel：委派工作并管理后台任务。" },
        ],
      },
      {
        heading: "要求",
        blocks: [
          { type: "paragraph", content: "ChatGPT 订阅，包括免费账号，或者 OpenAI API 密钥。使用会计入你的 Codex 使用额度。" },
          { type: "paragraph", content: "Node.js 18.18 或更高版本。" },
        ],
      },
      {
        heading: "安装",
        blocks: [
          { type: "paragraph", content: "在 Claude Code 中添加市场：" },
          { type: "code", label: "添加市场", content: "/plugin marketplace add openai/codex-plugin-cc" },
          { type: "paragraph", content: "安装插件：" },
          { type: "code", label: "安装插件", content: "/plugin install codex@openai-codex" },
          { type: "paragraph", content: "重新加载插件：" },
          { type: "code", label: "重新加载插件", content: "/reload-plugins" },
          { type: "paragraph", content: "然后运行：" },
          { type: "code", label: "检查设置", content: "/codex:setup" },
          { type: "paragraph", content: "/codex:setup 会告诉你 Codex 是否已经准备好。如果缺少 Codex，并且 npm 可用，它可以提示你安装 Codex。" },
          { type: "paragraph", content: "如果你希望自己安装 Codex，可以使用：" },
          { type: "code", label: "安装 Codex", content: "npm install -g @openai/codex" },
          { type: "paragraph", content: "如果 Codex 已经安装但还没有登录，运行：" },
          { type: "code", label: "登录 Codex", content: "!codex login" },
          { type: "paragraph", content: "安装完成后，你应该能看到下面列出的斜杠命令，以及 /agents 里的 codex:codex-rescue 子智能体。" },
          { type: "paragraph", content: "一个简单的首次运行方式是：" },
          { type: "code", label: "首次运行", content: "/codex:review --background\n/codex:status\n/codex:result" },
        ],
      },
      {
        heading: "/codex:review",
        blocks: [
          { type: "paragraph", content: "对当前工作运行一次普通的 Codex 审查。它提供的代码审查质量，与直接在 Codex 里运行 /review 相同。" },
          { type: "paragraph", content: "多文件变更的代码审查可能需要一些时间。通常建议在后台运行。" },
          { type: "paragraph", content: "在这些场景使用它：审查当前未提交的变更；审查当前分支相对 main 等基准分支的变化。" },
          { type: "paragraph", content: "使用 --base <ref> 可以做分支审查。它也支持 --wait 和 --background。它不可调向，也不接受自定义关注点文本。如果你希望挑战某个具体决策或风险区域，请使用 /codex:adversarial-review。" },
          { type: "code", label: "审查示例", content: "/codex:review\n/codex:review --base main\n/codex:review --background" },
          { type: "paragraph", content: "这个命令是只读的，不会执行任何修改。后台运行时，可以用 /codex:status 查看进度，用 /codex:cancel 取消正在执行的任务。" },
        ],
      },
      {
        heading: "/codex:adversarial-review",
        blocks: [
          { type: "paragraph", content: "运行一次可调向的审查，专门质疑当前实现和设计选择。" },
          { type: "paragraph", content: "它可以用来压力测试假设、取舍、故障模式，以及是否存在更安全或更简单的方案。" },
          { type: "paragraph", content: "它使用和 /codex:review 相同的审查目标选择方式，包括用 --base <ref> 做分支审查。它也支持 --wait 和 --background。不同的是，/codex:adversarial-review 可以在参数后接受额外的关注点文本。" },
          { type: "paragraph", content: "在这些场景使用它：发布前想挑战整体方向，而不只是检查代码细节；想把审查聚焦在设计选择、取舍、隐藏假设和替代方案上；想围绕认证、数据丢失、回滚、竞态条件或可靠性等具体风险做压力测试。" },
          { type: "code", label: "挑战式审查示例", content: "/codex:adversarial-review\n/codex:adversarial-review --base main challenge whether this was the right caching and retry design\n/codex:adversarial-review --background look for race conditions and question the chosen approach" },
          { type: "paragraph", content: "这个命令是只读的。它不会修复代码。" },
        ],
      },
      {
        heading: "/codex:rescue",
        blocks: [
          { type: "paragraph", content: "通过 codex:codex-rescue 子智能体把任务交给 Codex。" },
          { type: "paragraph", content: "在你希望 Codex 调查错误、尝试修复、继续之前的 Codex 任务，或用更小的模型做一次更快或更便宜的处理时使用它。" },
          { type: "paragraph", content: "根据任务和你选择的模型不同，这些任务可能需要很长时间。通常建议强制后台执行，或者把智能体移动到后台。" },
          { type: "paragraph", content: "它支持 --background、--wait、--resume 和 --fresh。如果你省略 --resume 和 --fresh，插件可以提示你继续当前仓库里最近一次 rescue 线程。" },
          { type: "code", label: "委派任务示例", content: "/codex:rescue investigate why the tests started failing\n/codex:rescue fix the failing test with the smallest safe patch\n/codex:rescue --resume apply the top fix from the last run\n/codex:rescue --model gpt-5.4-mini --effort medium investigate the flaky integration test\n/codex:rescue --model spark fix the issue quickly\n/codex:rescue --background investigate the regression" },
          { type: "paragraph", content: "你也可以直接要求把任务委派给 Codex：" },
          { type: "code", label: "自然语言委派", content: "Ask Codex to redesign the database connection to be more resilient." },
          { type: "paragraph", content: "如果没有传 --model 或 --effort，Codex 会选择自己的默认值。如果你说 spark，插件会把它映射到 gpt-5.3-codex-spark。后续 rescue 请求可以继续当前仓库里最近的 Codex 任务。" },
        ],
      },
      {
        heading: "状态、结果、取消和设置",
        blocks: [
          { type: "paragraph", content: "/codex:status 显示当前仓库正在运行和最近运行过的 Codex 任务。" },
          { type: "code", label: "查看状态", content: "/codex:status\n/codex:status task-abc123" },
          { type: "paragraph", content: "/codex:result 显示已完成任务保存下来的最终 Codex 输出。可用时，它还会包含 Codex 会话 ID，方便你用 codex resume <session-id> 直接重新打开那次运行。" },
          { type: "code", label: "查看结果", content: "/codex:result\n/codex:result task-abc123" },
          { type: "paragraph", content: "/codex:cancel 取消一个正在运行的后台 Codex 任务。" },
          { type: "code", label: "取消任务", content: "/codex:cancel\n/codex:cancel task-abc123" },
          { type: "paragraph", content: "/codex:setup 检查 Codex 是否已安装且已认证。如果缺少 Codex，并且 npm 可用，它可以提示你安装。你也可以用 /codex:setup 管理可选的审查门禁。" },
          { type: "code", label: "审查门禁", content: "/codex:setup --enable-review-gate\n/codex:setup --disable-review-gate" },
          { type: "paragraph", content: "审查门禁启用后，插件会使用 Stop hook，根据 Claude 的回复运行一次有针对性的 Codex 审查。如果审查发现问题，停止动作会被阻止，让 Claude 先处理这些问题。" },
          { type: "paragraph", content: "警告：审查门禁可能制造长时间运行的 Claude/Codex 循环，并快速消耗使用额度。只在你准备主动监控会话时启用它。" },
        ],
      },
      {
        heading: "典型流程",
        blocks: [
          { type: "paragraph", content: "发布前审查：" },
          { type: "code", label: "发布前审查", content: "/codex:review" },
          { type: "paragraph", content: "把问题交给 Codex：" },
          { type: "code", label: "委派问题", content: "/codex:rescue investigate why the build is failing in CI" },
          { type: "paragraph", content: "启动一个长时间运行的任务：" },
          { type: "code", label: "后台任务", content: "/codex:adversarial-review --background\n/codex:rescue --background investigate the flaky test" },
          { type: "paragraph", content: "然后这样查看：" },
          { type: "code", label: "查看后台任务", content: "/codex:status\n/codex:result" },
        ],
      },
      {
        heading: "Codex 集成",
        blocks: [
          { type: "paragraph", content: "Codex 插件封装了 Codex app server。它使用你环境中全局安装的 codex 二进制文件，并应用同一套配置。" },
          { type: "paragraph", content: "如果你想修改插件使用的默认推理强度或默认模型，可以在用户级或项目级 config.toml 中定义。例如，如果想让某个项目始终使用 gpt-5.4-mini，并把推理强度设为 high，可以在你启动 Claude 的目录根部创建 .codex/config.toml。" },
          { type: "code", label: "项目级配置", content: "model = \"gpt-5.4-mini\"\nmodel_reasoning_effort = \"high\"" },
          { type: "paragraph", content: "配置会按这些位置读取：~/.codex/config.toml 中的用户级配置；.codex/config.toml 中的项目级覆盖；项目被信任后，项目级覆盖才会加载。" },
          { type: "paragraph", content: "委派任务和任何停止门禁运行，也可以直接在 Codex 里继续。你可以用 /codex:result 或 /codex:status 得到的具体会话 ID 运行 codex resume，也可以从列表中选择。这样你就可以在 Codex 里审查或继续那项工作。" },
        ],
      },
      {
        heading: "常见问题",
        blocks: [
          { type: "paragraph", content: "如果你已经在这台机器上登录了 Codex，这里应该可以直接使用同一个账号。这个插件使用你本地的 Codex CLI 认证状态。" },
          { type: "paragraph", content: "如果你今天只使用 Claude Code，还没有用过 Codex，你需要用 ChatGPT 账号或 API 密钥登录 Codex。Codex 可以通过 ChatGPT 订阅使用，codex login 同时支持 ChatGPT 和 API 密钥登录。运行 /codex:setup 检查 Codex 是否准备好；如果没有准备好，可以使用 !codex login。" },
          { type: "paragraph", content: "这个插件不会使用单独的 Codex 运行时。它通过同一台机器上的本地 Codex CLI 和 Codex app server 委派任务。" },
          { type: "paragraph", content: "这意味着：它使用你直接使用 Codex 时的同一个安装；它使用同一个本地认证状态；它使用同一个仓库检出和本机环境。" },
          { type: "paragraph", content: "如果你已经在使用 Codex，插件会读取同一套配置。因为插件使用你的本地 Codex CLI，所以已有登录方式和配置仍然适用。如果你需要把内置 OpenAI provider 指向不同端点，可以在 Codex 配置里设置 openai_base_url。" },
        ],
      },
    ],
  },
  {
    id: "claude-code-workflows-readme-translation",
    sourceUrl: "https://github.com/shinpr/claude-code-workflows",
    translationMode: "fullTranslation",
    title: "Claude Code Workflows：从需求、设计、实现到验证的端到端开发流程",
    originalTitle: "Claude Code Workflows",
    notice: "",
    showSourceAddress: true,
    hideSourceNoticeLink: true,
    hideArticleSiteLink: true,
    hideLead: true,
    sections: [
      {
        heading: "Claude Code Workflows",
        blocks: [
          { type: "paragraph", content: "面向 Claude Code 的端到端开发工作流，让产出的代码与设计文档和测试保持一致。专门的智能体分别处理需求、设计、实现和质量检查，因此最终得到的是能通过测试、并且匹配设计文档的代码。" },
        ],
      },
      {
        heading: "快速开始",
        blocks: [
          { type: "subheading", content: "应该从哪个插件开始" },
          { type: "paragraph", content: "后端、接口、命令行工具或通用编程：安装 dev-workflows。" },
          { type: "paragraph", content: "React / TypeScript 前端：安装 dev-workflows-frontend。" },
          { type: "paragraph", content: "全栈，后端 + React：安装 dev-workflows-fullstack。它是单个插件，替代同时安装两个插件。" },
          { type: "paragraph", content: "如果你已经有自己的编排，只想要规则：安装 dev-skills，只包含技能。" },
          { type: "subheading", content: "通用设置" },
          { type: "code", label: "通用设置", content: "# 1. 启动 Claude Code\nclaude\n\n# 2. 添加市场\n/plugin marketplace add shinpr/claude-code-workflows" },
          { type: "subheading", content: "安装并开始构建" },
          { type: "code", label: "安装并开始构建", content: "# 后端或通用开发\n/plugin install dev-workflows@claude-code-workflows\n/reload-plugins\n/recipe-implement <your feature>\n\n# 前端\n/plugin install dev-workflows-frontend@claude-code-workflows\n/reload-plugins\n/recipe-front-design <your feature>\n\n# 全栈，单个插件\n/plugin install dev-workflows-fullstack@claude-code-workflows\n/reload-plugins\n/recipe-fullstack-implement \"Add user authentication with JWT + login form\"\n\n# 或者从已有全栈工作计划执行\n/recipe-fullstack-build" },
          { type: "paragraph", content: "全栈 recipe 会为每一层创建独立设计文档，后端和前端分别处理，通过 design-sync 验证跨层一致性，并根据文件名模式把任务路由给合适的执行器。" },
          { type: "paragraph", content: "迁移提醒：recipe-fullstack-* 属于 dev-workflows-fullstack，不属于 dev-workflows。如果你做全栈工作，只安装 dev-workflows-fullstack。" },
        ],
      },
      {
        heading: "可选扩展与只安装技能",
        blocks: [
          { type: "paragraph", content: "可选插件覆盖工作流相邻阶段：claude-code-discover 把功能想法转成基于证据的产品需求文档；metronome 检测走捷径的行为，并提醒 Claude 一步一步推进；linear-prism 把需求转成结构化 Linear 任务；pr-review 用 Claude Code 或 Codex 审查 GitHub PR。" },
          { type: "code", label: "可选插件", content: "/plugin install discover@claude-code-workflows\n/plugin install metronome@claude-code-workflows\n/plugin install linear-prism@claude-code-workflows\n/plugin install pr-review@claude-code-workflows" },
          { type: "paragraph", content: "如果你已经有自己的编排，例如自定义提示词、脚本或 CI 驱动循环，只想要最佳实践指南，可以使用 dev-skills。如果你希望 Claude 端到端规划、执行和验证，则安装 dev-workflows。" },
          { type: "paragraph", content: "dev-skills 的特点是最小上下文占用，不加载智能体或 recipe 技能；不改变现有工作流也能接入最佳实践；可以作为你自己编排器的规则层。" },
          { type: "code", label: "只安装技能", content: "/plugin install dev-skills@claude-code-workflows" },
          { type: "paragraph", content: "技能会在相关场景自动加载。coding-principles 会在实现阶段激活，testing-principles 会在写测试阶段激活。" },
          { type: "code", label: "切换插件", content: "# dev-skills -> dev-workflows\n/plugin uninstall dev-skills@claude-code-workflows\n/plugin install dev-workflows@claude-code-workflows\n\n# dev-workflows -> dev-skills\n/plugin uninstall dev-workflows@claude-code-workflows\n/plugin install dev-skills@claude-code-workflows" },
          { type: "paragraph", content: "警告：dev-skills 与 dev-workflows / dev-workflows-frontend / dev-workflows-fullstack 共享同一套技能。安装多个会让技能描述在系统上下文里重复出现。Claude Code 会把技能描述限制在上下文窗口的大约 2%。超过这个限制会导致技能被静默忽略。全栈工作只安装 dev-workflows-fullstack。" },
        ],
      },
      {
        heading: "工作原理",
        blocks: [
          { type: "paragraph", content: "请求会先由 requirement-analyzer 判断复杂度。大任务会经过产品需求文档、代码库分析和设计，再进入实现；中等任务会先做代码库分析；小任务可以直接实现。" },
          { type: "paragraph", content: "随后 technical-designer、code-verifier、document-reviewer、design-sync、acceptance-test-generator、work-planner、task-decomposer、task-executor 和 quality-fixer 依次参与，把需求变成经过验证、可以提交的代码。" },
          { type: "paragraph", content: "诊断流程会在 investigator 和 verifier 之间循环，直到路径覆盖足够，再交给 solver 进行取舍分析。" },
          { type: "paragraph", content: "逆向工程分两阶段运行。先生成产品需求文档，每个发现的功能一个文档，然后设计文档复用这个范围，不重新发现。" },
          { type: "paragraph", content: "每个阶段都在新的智能体上下文中运行，所以前面的步骤不会膨胀上下文，也不会干扰后面的决策。" },
        ],
      },
      {
        heading: "工作流 Recipe",
        blocks: [
          { type: "paragraph", content: "所有工作流入口都使用 recipe- 前缀，以便和知识技能区分。输入 /recipe- 并使用 tab 补全可以查看所有可用 recipe。" },
          { type: "subheading", content: "后端与通用开发" },
          { type: "paragraph", content: "/recipe-implement 用于端到端功能开发。/recipe-task 用于精准执行单个任务。/recipe-design 用于创建设计文档。/recipe-plan 从设计生成工作计划。/recipe-prepare-implementation 验证实现准备度并解决缺口。/recipe-build 从已有任务计划执行。/recipe-review 按设计文档验证代码。/recipe-diagnose 调查问题并推导方案。/recipe-reverse-engineer 从现有代码生成产品需求文档和设计文档。/recipe-add-integration-tests 给现有代码增加集成或端到端测试。/recipe-update-doc 带审查更新已有设计文档。" },
          { type: "subheading", content: "前端开发" },
          { type: "paragraph", content: "前端插件增加了 React 专用智能体，包括组件架构、Testing Library、TypeScript 优先的质量检查，以及可从可选原型代码生成界面规格。" },
          { type: "paragraph", content: "/recipe-front-design 创建界面规格和前端设计文档。/recipe-front-plan 生成前端工作计划。/recipe-front-build 执行前端任务计划。/recipe-front-adjust 结合 MCP 验证调整已实现界面。/recipe-front-review 按设计文档验证代码。/recipe-task、/recipe-diagnose 和 /recipe-update-doc 在两个插件中共享。" },
        ],
      },
      {
        heading: "专门智能体",
        blocks: [
          { type: "paragraph", content: "共享智能体包括：requirement-analyzer、codebase-analyzer、work-planner、task-decomposer、code-reviewer、document-reviewer、design-sync、investigator、verifier、solver 和 security-reviewer。" },
          { type: "paragraph", content: "后端专用智能体包括：prd-creator、technical-designer、scope-discoverer、code-verifier、acceptance-test-generator、integration-test-reviewer、task-executor、quality-fixer 和 rule-advisor。" },
          { type: "paragraph", content: "前端专用智能体包括：prd-creator、ui-spec-designer、ui-analyzer、technical-designer-frontend、task-executor-frontend、code-verifier、quality-fixer-frontend、rule-advisor 和 design-sync。" },
        ],
      },
      {
        heading: "内置最佳实践",
        blocks: [
          { type: "paragraph", content: "后端插件包含可用于任何语言的成熟最佳实践：编码原则、测试原则、实现方法、文档标准和外部资源上下文。" },
          { type: "paragraph", content: "外部资源上下文是双层文件，记录如何访问仓库外资源，例如设计源、设计系统、接口 schema、基础设施即代码等。" },
          { type: "paragraph", content: "前端插件内置 React 和 TypeScript 专用规则。" },
        ],
      },
      {
        heading: "典型工作流",
        blocks: [
          { type: "subheading", content: "后端功能开发" },
          { type: "code", label: "后端功能开发", content: "/recipe-implement \"Add user authentication with JWT\"" },
          { type: "paragraph", content: "你会得到：带验收标准的产品需求文档、必要时的架构决策记录，以及设计文档；拆成可提交任务的工作计划；使用测试驱动开发实现的后端代码，经过类型检查和 lint；完成前按设计文档做代码审查。" },
          { type: "subheading", content: "前端功能开发" },
          { type: "code", label: "前端功能开发", content: "/recipe-front-design \"Build a user profile dashboard\"\n\n# 然后运行：\n/recipe-front-build" },
          { type: "paragraph", content: "流程包括判断规模、捕获设计源和视觉验证访问方式、并行收集事实、放置可选原型代码、生成界面规格，以及让前端设计文档继承界面规格决策。" },
          { type: "paragraph", content: "界面规格存在的原因：原型捕获视觉表面，但很少覆盖加载、错误、空状态和部分状态。界面规格会捕获这些状态与展示矩阵，并追踪到设计文档和测试骨架中，让集成问题更早暴露。" },
          { type: "subheading", content: "全栈工作流" },
          { type: "code", label: "全栈工作流", content: "/recipe-fullstack-implement \"Add user authentication with JWT + React login form\"" },
          { type: "paragraph", content: "全栈流程会生成覆盖整个功能的产品需求文档、界面规格、每层独立设计文档，通过 design-sync 验证跨层一致性，再把工作计划组合成垂直功能切片，并按层路由任务。" },
          { type: "subheading", content: "界面调整、快速修复、代码审查和诊断" },
          { type: "code", label: "常用命令", content: "/recipe-front-adjust \"Tighten Card spacing and align action buttons with the design source\"\n/recipe-task \"Fix validation error message\"\n/recipe-review\n/recipe-diagnose \"API returns 500 error on user login\"\n/recipe-reverse-engineer \"src/auth module\"" },
          { type: "paragraph", content: "如果你在处理没有文档的遗留代码，这些命令会生成产品需求文档和设计文档，让代码库更适合 AI 协作。" },
        ],
      },
      {
        heading: "仓库结构、常见问题和许可证",
        blocks: [
          { type: "code", label: "仓库结构", content: "claude-code-workflows/\n├── .claude-plugin/\n│   └── marketplace.json\n├── agents/\n├── skills/\n├── LICENSE\n└── README.md" },
          { type: "paragraph", content: "不太需要学习特殊命令。后端使用 /recipe-implement，前端使用 /recipe-front-design。插件会自动处理其他事情。" },
          { type: "paragraph", content: "如果出现错误，quality-fixer 智能体会自动修复大多数问题，例如测试失败、类型错误和 lint 问题。如果无法自动修复，你会得到清晰的处理建议。" },
          { type: "paragraph", content: "codex-workflows 为 Codex CLI 提供相同的端到端开发工作流。概念相同，都是用专门子智能体处理需求、设计、实现和质量检查，但适配 Codex CLI 环境。" },
          { type: "paragraph", content: "Recipe 把 docs/plans/ 视为临时工作状态，不应该提交。产品需求文档、架构决策记录、界面规格和设计文档位于各自目录，应该提交。" },
          { type: "paragraph", content: "MIT 许可证。可以自由使用、修改和分发。" },
        ],
      },
    ],
  },
  {
    id: "primer-ai-agent-milestone-workflow-translation",
    sourceUrl: "https://github.com/armgabrielyan/primer",
    translationMode: "fullTranslation",
    title: "Primer：让 AI 编程按已验证里程碑推进",
    originalTitle: "Primer",
    notice: "",
    showSourceAddress: true,
    hideSourceNoticeLink: true,
    hideArticleSiteLink: true,
    hideLead: true,
    sections: [
      {
        heading: "Primer",
        blocks: [
          { type: "paragraph", content: "Primer 帮助你用 AI 编程智能体构建真实软件，一次推进一个已经验证的里程碑。" },
          { type: "paragraph", content: "主要工作发生在你的 AI 编程智能体里。primer CLI 会设置工作区、验证前置条件，并在底层驱动里程碑工作流。" },
          { type: "paragraph", content: "与其把一个巨大而模糊的任务交给智能体，Primer 会给你一个里程碑契约、一个验证步骤和一个清晰的下一步动作。" },
          { type: "paragraph", content: "如果你想从真实工作区开始、让智能体专注当前步骤、进入下一步前先验证进度，并且一边构建一边理解系统，Primer 很适合。" },
          { type: "paragraph", content: "当前 recipe：cli-tool 用 Python 构建实用的任务追踪命令行工具；interpreter-mini 用 Python 构建一个小型表达式语言；operating-system 从引导加载器到 shell 构建一个 x86 操作系统。" },
        ],
      },
      {
        heading: "从这里开始",
        blocks: [
          { type: "paragraph", content: "如果你想以最快方式从零开始，在 AI 编程智能体里构建：" },
          { type: "code", label: "最快开始", content: "primer list\nprimer init cli-tool --tool codex --track learner --path ~/projects/task-cli-demo\ncd ~/projects/task-cli-demo\nprimer doctor cli-tool --milestone 01-bootstrap" },
          { type: "paragraph", content: "使用终端做设置：primer list 显示目录；primer init 创建一个独立项目工作区，并为它生成 AI 工具说明；primer doctor 检查本地工具链是否已经准备好第一个里程碑。" },
          { type: "paragraph", content: "然后在你的 AI 编程智能体中打开生成的工作区，并在那里使用 Primer 工作流动作。" },
          { type: "paragraph", content: "primer-build 只实现当前里程碑范围；primer-verify 运行里程碑验证，并在成功时标记为已验证；primer-next-milestone 只有验证通过后才解锁下一个里程碑；primer-explain 显示当前里程碑的更深入解释；primer-status 显示当前里程碑、验证状态、重试次数和进度。" },
          { type: "paragraph", content: "Primer 的设计方式是：在普通 shell 里，你主要用 primer 做设置、诊断和实用操作；在受支持 AI 工具生成的工作区里，你通过生成动作完成真正的里程碑工作。如果你刚接触 Primer，请从 --track learner 开始。" },
        ],
      },
      {
        heading: "指南和 5 分钟演示",
        blocks: [
          { type: "paragraph", content: "Primer 的公开文档有三个主要入口：Learn With Primer 面向新手，聚焦 cli-tool、learner 轨道和理解循环；Build Safely With Primer 面向执行，聚焦逐里程碑交付和 JSON 包装器；Use Primer In An Existing Repository 面向已有仓库，围绕 workstream、边界分析和仓库本地状态构建。" },
          { type: "paragraph", content: "目前最好的快速演示路径，是面向新手的 cli-tool recipe。它展示初始化工作区、检查当前里程碑、在代码存在前观察验证失败、实现一个里程碑、成功验证它，以及安全前进。" },
          { type: "code", label: "5 分钟演示", content: "primer init cli-tool --tool codex --track learner --path ~/projects/task-cli-demo\ncd ~/projects/task-cli-demo\nprimer doctor cli-tool --milestone 01-bootstrap" },
          { type: "paragraph", content: "然后在 AI 工具里打开工作区，并使用 primer-status、primer-build、primer-verify 和 primer-next-milestone。" },
        ],
      },
      {
        heading: "Primer 如何工作",
        blocks: [
          { type: "paragraph", content: "Primer 有两层：设置层和工作层。设置层由 primer CLI 创建工作区、检查环境并管理工作流状态。工作层由你的 AI 编程智能体在这个工作区中使用生成的 Primer 动作，按里程碑构建。" },
          { type: "paragraph", content: "实际使用时，你先接触终端来初始化工作区；你大部分时间在 AI 编程智能体里度过；Primer 验证决定一个里程碑是否真正完成。" },
          { type: "paragraph", content: "CLI 是重要的基础设施，但它不是主要日常界面。" },
        ],
      },
      {
        heading: "为什么需要 Primer",
        blocks: [
          { type: "paragraph", content: "多数 AI 编程工作流会以可预测的方式失败：任务太宽泛；智能体太早实现未来步骤；没有可靠的完成检查；进度很难看清。" },
          { type: "paragraph", content: "Primer 把这些问题变成可重复的循环：从 recipe 初始化一个独立项目工作区；加载当前里程碑契约；只构建那个范围；运行验证；只有验证通过后才前进。" },
          { type: "paragraph", content: "结果更像一个带引导的实验室，而不是开放式提示词。" },
        ],
      },
      {
        heading: "Primer 是否适合新手",
        blocks: [
          { type: "paragraph", content: "工作流适合新手。当前 recipe 目录还不是广泛面向新手的。这个区别很重要。" },
          { type: "paragraph", content: "Primer 本身为学生、初级开发者和借助 AI 学习的人设计，尽量容易接近。当前旗舰 recipe operating-system 仍然是一个高级系统项目，需要真实工具链和底层概念。" },
          { type: "paragraph", content: "如果你是新手或初学者，推荐路径是：使用 --track learner；从 cli-tool recipe 开始；尽早运行 primer doctor，让工具问题变清楚；在每个里程碑中使用 primer explain 和 primer verify；期待逐步学习，而不是一开始就理解整个系统。" },
          { type: "paragraph", content: "如果你完全没有编程经验，cli-tool 是最好的起点。更有野心的 operating-system recipe 更适合作为高级引导实验室。" },
        ],
      },
      {
        heading: "适合谁",
        blocks: [
          { type: "paragraph", content: "Primer 面向希望用 AI 工具构建时有结构的人：希望有解释、检查点和可见进度的学习者；希望更严格控制范围、更安全迭代的构建者；希望创建可复用、基于里程碑学习路径的教育者和 recipe 作者。" },
          { type: "paragraph", content: "如果你想尝试有野心的项目，但不想一次性把整个问题交给智能体，Primer 就是入口。" },
          { type: "paragraph", content: "Primer 也计划成长为一个社区引导实验室库。如果你想帮助创建新 recipe，或改善现有 recipe 的教育体验，请查看贡献文档和社区 recipe 文档。" },
        ],
      },
      {
        heading: "安装",
        blocks: [
          { type: "paragraph", content: "选择一种安装路径。安装 primer CLI 是因为它会引导并支持智能体工作流。" },
          { type: "code", label: "推荐快速安装", content: "curl -sSf https://raw.githubusercontent.com/armgabrielyan/primer/main/install.sh | sh" },
          { type: "code", label: "Homebrew", content: "brew install armgabrielyan/tap/primer" },
          { type: "code", label: "npm / npx", content: "npm install -g @armengabrielyan/primer\n\n# 一次性使用\nnpx @armengabrielyan/primer list" },
          { type: "paragraph", content: "@armengabrielyan/primer 包会在安装时下载与你平台匹配的预构建 primer 二进制文件。" },
          { type: "code", label: "Cargo", content: "cargo install primer" },
          { type: "paragraph", content: "也可以从 GitHub Releases 页面下载预构建归档，或者从源码构建。" },
          { type: "code", label: "从源码构建", content: "git clone https://github.com/armgabrielyan/primer\ncd primer\ncargo build --release\n\n# 二进制文件位置\n./target/release/primer" },
          { type: "code", label: "从本地源码安装", content: "cargo install --path ." },
          { type: "code", label: "安装后检查", content: "primer --help\nprimer list" },
          { type: "code", label: "Shell 补全", content: "primer completions zsh\nprimer completions bash\nprimer completions fish" },
        ],
      },
      {
        heading: "AI 工具集成",
        blocks: [
          { type: "paragraph", content: "Primer 有这些原生工作区适配器：Claude Code、Codex、OpenCode、Gemini CLI 和 Cursor。" },
          { type: "paragraph", content: "Primer 被设计为在你的 AI 编程智能体里使用。primer init 会把工具专属文件生成到工作区，让工作流出现在项目工作真正发生的地方。" },
          { type: "code", label: "统一初始化形状", content: "primer init <recipe-id> --tool <claude|codex|opencode|gemini|cursor> --path ~/projects/my-workspace" },
          { type: "paragraph", content: "Claude Code 会生成 CLAUDE.md 和 .claude/commands/。Codex 会生成 AGENTS.md 和 .agents/skills/。OpenCode 会生成 AGENTS.md 和 .opencode/skills/。Gemini CLI 会生成 GEMINI.md 和 .gemini/skills/。Cursor 会生成 AGENTS.md 和 .cursor/skills/。" },
          { type: "paragraph", content: "这些生成动作是主要用户体验。CLI 提供它们依赖的底层状态操作、验证和设置支持。如果你偏好的 AI 工具能遵循工作区说明并运行本地 primer CLI，Primer 通常也能适配那种工作流。" },
        ],
      },
      {
        heading: "可用 Recipe 和轨道",
        blocks: [
          { type: "paragraph", content: "当前目录包括 cli-tool、interpreter-mini 和 operating-system。cli-tool 是初学者、第一次使用 Primer 或想快速获得第一次成功时的起点。interpreter-mini 适合完成 cli-tool 后，想做更偏概念的解析和求值项目的人。operating-system 是高级项目，建议使用 --track learner，把它当作引导实验室。" },
          { type: "paragraph", content: "Primer 支持两种交互风格：learner 和 builder。learner 轨道让智能体解释步骤，一边构建一边教学，并在自然检查点暂停。builder 轨道让智能体直接实现，尽量少讲解。" },
          { type: "code", label: "轨道示例", content: "primer init operating-system --tool codex --track learner --path ~/projects/my-os\nprimer init operating-system --tool codex --track builder --path ~/projects/my-os" },
          { type: "paragraph", content: "如果没有传 --track，Primer 默认使用 learner。之后可以不重新初始化就切换。" },
          { type: "code", label: "切换轨道", content: "primer track builder\nprimer track learner" },
        ],
      },
      {
        heading: "智能体工作流动作",
        blocks: [
          { type: "paragraph", content: "工作区初始化后，这是使用 Primer 的主要方式。" },
          { type: "paragraph", content: "primer-build 加载当前里程碑范围，并只实现那一步。primer-track 切换工作区的 learner 或 builder 轨道。primer-status 显示当前里程碑、验证状态和进度。primer-explain 显示当前里程碑的更深入解释。primer-verify 运行里程碑验证，并在成功时标记为已验证。primer-next-milestone 只有验证通过后才解锁下一个里程碑。" },
          { type: "paragraph", content: "Primer 也暴露匹配的 CLI 命令，例如 primer build、primer track、primer status、primer explain、primer verify 和 primer next-milestone，但默认体验是在 AI 编程智能体里使用生成动作。" },
          { type: "paragraph", content: "当你需要机器可读形式时，可以使用 primer status --json、primer verify --json、primer next-milestone --json 和 primer build --json。" },
        ],
      },
      {
        heading: "CLI 设置命令",
        blocks: [
          { type: "paragraph", content: "直接使用 CLI 做设置、诊断和终端实用操作。" },
          { type: "paragraph", content: "primer list 列出可用 recipe。primer recipe lint 检查本地 recipe 结构和里程碑质量指导。primer milestone lint 检查一个工作区、recipe 或 workstream 中的里程碑契约和边界。primer init 创建工作区并生成适配器文件。primer doctor 检查某个 recipe 里程碑的本地前置条件。" },
          { type: "paragraph", content: "primer workstream list 列出当前仓库已初始化的 brownfield workstream。primer workstream analyze 分析仓库边界并建议安全的第一里程碑候选。primer workstream init 在当前仓库中为一个 brownfield workstream 引导 Primer。primer workstream switch 激活并恢复另一个已初始化的 workstream。primer track 切换当前工作区的 learner 或 builder 轨道。primer completions 生成 shell 补全脚本。" },
          { type: "paragraph", content: "有用的安全标志：primer init --dry-run 会显示将发生什么，但不写文件。primer init --force 允许初始化到非空目录。" },
          { type: "code", label: "已有仓库 workstream", content: "primer workstream list\nprimer workstream analyze --goal \"Reduce auth pipeline complexity\"\nprimer workstream init auth-refactor --goal \"Reduce auth pipeline complexity\" --tool codex --track learner\nprimer workstream switch auth-refactor" },
          { type: "paragraph", content: "primer workstream init 还会创建 .primer/workstreams/<workstream-id>/workstream-intent.md，用来保存目标、非目标、约束和完成条件。" },
        ],
      },
      {
        heading: "JSON 示例、工作区模型和故障排除",
        blocks: [
          { type: "paragraph", content: "Primer 的 JSON 输出面向小型包装器和自动化，不只是为了测试。仓库包含 status-summary.sh、verify-summary.sh 和 workstream-dashboard.sh 示例。" },
          { type: "code", label: "JSON 示例", content: "bash examples/json/status-summary.sh /path/to/workspace\nbash examples/json/verify-summary.sh /path/to/workspace\nbash examples/json/workstream-dashboard.sh /path/to/repository" },
          { type: "paragraph", content: "Primer 使用两个独立位置：primer 仓库保存 recipe、适配器生成、CLI 引擎和共享工作流逻辑；你生成的项目工作区保存你正在构建的项目代码和 Primer 状态；AI 编程智能体是读取、构建、验证和推进里程碑的主要位置。" },
          { type: "paragraph", content: "不要在 primer 仓库本身里面构建。primer init 是为了创建或准备一个独立工作区。primer init 后，生成的工作区包含智能体真正要构建的项目文件、当前 Primer 状态，以及工具专属说明和工作流动作。" },
          { type: "paragraph", content: "对已有仓库中的 brownfield 工作，Primer 也可以在仓库本地 workstream 模式运行。它会把作者维护的 workstream 文件放在 .primer/workstreams/<workstream-id>/，把运行时状态放在 .primer/runtime/workstreams/<workstream-id>/，并通过 primer workstream switch 在根适配器上下文中保持一个活跃 workstream。" },
          { type: "paragraph", content: "如果不确定本地工具链是否已经为当前里程碑准备好，在 primer init 后运行 primer doctor。如果 AI 工具看不到生成的 Primer 工作流动作，确认你打开的是生成的工作区，而不是 primer 仓库。如果 AI 工具无法运行 primer，先安装或构建 CLI，并确认它在 PATH 中。primer init 默认安全，只有在你明确想初始化到非空目录时才使用 --force。" },
        ],
      },
      {
        heading: "贡献和许可证",
        blocks: [
          { type: "paragraph", content: "Primer 不只面向使用 recipe 的人，也面向想要编写 recipe 的人。贡献工作流、质量标准和社区方向见 CONTRIBUTING.md。如果你想提出新的社区学习路径，请从 docs/community-recipes.md 开始。" },
          { type: "paragraph", content: "Primer 使用 MIT 许可证。" },
        ],
      },
    ],
  },
];
