export const navItems = [
  { label: '案例', href: '/cases' },
  { label: '学习', href: '/learn' },
  { label: '工具', href: '/tools' },
];

export const caseTypeFilters = [
  '全部类型',
  '数据看板',
  '官网',
  '客户管理',
  '提示词工具',
  'SaaS 产品',
  '游戏',
  '音乐',
  '教育',
  '电商',
  '内容工具',
  '其他',
];

const submitters = {
  david: {
    id: 'david',
    name: 'David',
    role: '独立开发者',
    bio: '关注 AI 编程、产品设计和独立开发。',
    avatar: '',
    email: '',
    wechat: '',
    douyin: '',
    douyinUrl: '',
    xiaohongshu: '',
    xiaohongshuUrl: '',
    website: '',
  },
  lin: {
    id: 'lin',
    name: 'Lin',
    role: '产品设计师',
    bio: '长期拆解 AI 生成界面和原型工作流。',
    avatar: '',
    email: '',
    wechat: '',
    douyin: '',
    douyinUrl: '',
    xiaohongshu: '',
    xiaohongshuUrl: '',
    website: '',
  },
  mia: {
    id: 'mia',
    name: 'Mia',
    role: '产品经理',
    bio: '关注从需求表达、工具选择到产品上线的完整过程。',
    avatar: '',
    email: '',
    wechat: '',
    douyin: '',
    douyinUrl: '',
    xiaohongshu: '',
    xiaohongshuUrl: '',
    website: '',
  },
  uicodingEditor: {
    id: 'uicoding-editor',
    name: 'UIcoding 编辑部',
    role: '外部精选案例',
    bio: 'UIcoding 编辑部持续精选值得学习的 AI Coding 作品，用于拆解产品结构、界面设计和 AI Coding 思路。',
    avatar: '',
    email: '',
    wechat: '',
    douyin: '',
    douyinUrl: '',
    xiaohongshu: '',
    xiaohongshuUrl: '',
    website: '',
  },
};

const categorySlugs = {
  数据看板: 'dashboard',
  官网: 'landing-page',
  客户管理: 'crm',
  提示词工具: 'prompt-tool',
  'SaaS 产品': 'saas',
  游戏: 'game',
  音乐: 'music',
  教育: 'education',
  电商: 'ecommerce',
  内容工具: 'content-tool',
};

function createDetailSections(item) {
  return [
    {
      id: 'hero-structure',
      title: '首屏结构',
      description: `${item.title} 如何组织首屏信息、核心内容和主要操作入口。`,
      image: '',
      imageAlt: `${item.title} 首屏结构截图`,
      points: ['核心信息前置', '操作入口清晰', '页面层级明确'],
    },
    {
      id: 'core-features',
      title: '核心功能',
      description: '展示作品中最重要的功能模块，以及这些模块如何帮助用户完成任务。',
      image: '',
      imageAlt: `${item.title} 核心功能截图`,
      points: ['功能边界清晰', '状态反馈明确', '信息展示易扫描'],
    },
    {
      id: 'ui-details',
      title: '界面细节',
      description: '拆解按钮、卡片、筛选、列表等细节如何提升整体使用体验。',
      image: '',
      imageAlt: `${item.title} 界面细节截图`,
      points: ['组件风格统一', '交互反馈克制', '内容密度适中'],
    },
    {
      id: 'ai-coding-process',
      title: 'AI 编程构建过程',
      description: '说明这个作品如何通过需求拆解、提示词、组件规划和多轮修改完成。',
      image: '',
      imageAlt: `${item.title} AI 编程构建过程截图`,
      points: ['先描述页面目标', '再拆分组件结构', '最后统一视觉细节'],
    },
  ];
}

function buildCase({ categorySlug, detailSections, slug, submitterId = 'david', websiteUrl = '', ...item }) {
  const finalSlug = slug ?? item.id;
  const finalCategorySlug = categorySlug ?? categorySlugs[item.category] ?? 'other';

  return {
    ...item,
    slug: finalSlug,
    categorySlug: finalCategorySlug,
    href: `/cases/${finalCategorySlug}/${finalSlug}`,
    websiteUrl,
    submitter: submitters[submitterId],
    detailSections: detailSections ?? createDetailSections(item),
  };
}

const externalCopyrightNote =
  '该案例为 UIcoding 外部精选内容，用于学习产品结构、界面设计和 AI Coding 思路。请访问原始来源查看完整信息。';

function createExternalDetailSections(item) {
  return [
    {
      id: 'structure',
      title: '作品结构',
      description: '这个案例适合学习如何组织页面信息、核心模块和主要操作入口。',
      image: '',
      imageAlt: `${item.title} 作品结构示意图`,
      points: ['核心信息前置', '模块边界清晰', '入口清楚'],
    },
    {
      id: 'features',
      title: '核心功能',
      description: '从功能组织上看，这个作品把用户最常用的任务放在更明显的位置。',
      image: '',
      imageAlt: `${item.title} 核心功能示意图`,
      points: ['任务路径明确', '状态反馈清楚', '内容易扫描'],
    },
    {
      id: 'uicoding-review',
      title: 'UIcoding 拆解',
      description: '这个案例可以作为 AI Coding 练习素材，重点学习需求拆解、组件规划和视觉统一。',
      image: '',
      imageAlt: `${item.title} UIcoding 案例拆解示意图`,
      points: ['先写清楚页面目标', '再拆分组件结构', '最后统一视觉细节'],
    },
  ];
}

export const cases = [
  buildCase({
    id: 'flowpilot-dashboard',
    slug: 'flowpilot-dashboard',
    title: 'FlowPilot 数据看板',
    description: '使用 AI 辅助完成的运营数据看板，展示指标建模、筛选状态和趋势复盘。',
    category: '数据看板',
    categorySlug: 'dashboard',
    tools: ['Codex'],
    tags: ['数据看板', '运营分析'],
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 1248,
    likeCount: 86,
    submitterId: 'david',
  }),
  buildCase({
    id: 'prompt-studio',
    slug: 'prompt-studio',
    title: 'Prompt Studio',
    description: '用于整理、测试和复用提示词的轻量工具，适合产品和设计团队沉淀 AI 工作流。',
    category: '提示词工具',
    categorySlug: 'prompt-tool',
    tools: ['Cursor'],
    tags: ['提示词', '工作流'],
    visualType: 'prompt',
    publishedAt: '2026-06-12',
    viewCount: 986,
    likeCount: 72,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'founder-crm',
    slug: 'founder-crm',
    title: 'Founder CRM',
    description: '面向独立开发者的客户关系管理工具，聚焦线索记录、跟进状态和成交节奏。',
    category: '客户管理',
    categorySlug: 'crm',
    tools: ['Claude Code'],
    tags: ['客户管理', 'SaaS'],
    visualType: 'crm',
    publishedAt: '2026-06-10',
    viewCount: 842,
    likeCount: 64,
    submitterId: 'mia',
  }),
  buildCase({
    id: 'launchkit',
    slug: 'launchkit',
    title: 'LaunchKit 官网',
    description: '一个用于展示产品定位、核心卖点和转化入口的 AI 生成官网案例。',
    category: '官网',
    categorySlug: 'landing-page',
    tools: ['Lovable'],
    tags: ['官网', '产品展示'],
    visualType: 'landing',
    publishedAt: '2026-06-08',
    viewCount: 1136,
    likeCount: 79,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'ai-resume-builder',
    slug: 'ai-resume-builder',
    title: 'AI Resume Builder',
    description: '帮助求职者快速生成简历内容和版式的 AI 工具，覆盖信息整理、语气优化和导出前检查。',
    category: 'SaaS 产品',
    categorySlug: 'saas',
    tools: ['Cursor'],
    tags: ['简历', 'AI 工具'],
    visualType: 'landing',
    publishedAt: '2026-06-06',
    viewCount: 756,
    likeCount: 41,
    submitterId: 'mia',
  }),
  buildCase({
    id: 'saas-pricing-page',
    slug: 'saas-pricing-page',
    title: 'SaaS Pricing Page',
    description: '围绕套餐层级、权益对比和行动按钮设计的价格页案例，适合学习转化型页面结构。',
    category: '官网',
    categorySlug: 'landing-page',
    tools: ['v0'],
    tags: ['价格页', 'SaaS'],
    visualType: 'landing',
    publishedAt: '2026-06-05',
    viewCount: 689,
    likeCount: 38,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'taskflow-project',
    slug: 'taskflow',
    title: 'TaskFlow 项目管理',
    description: '面向小团队的项目管理界面，展示任务分组、进度状态和 AI 辅助复盘流程。',
    category: 'SaaS 产品',
    categorySlug: 'saas',
    tools: ['Codex'],
    tags: ['项目管理', '工作流'],
    visualType: 'dashboard',
    publishedAt: '2026-06-04',
    viewCount: 934,
    likeCount: 55,
    submitterId: 'david',
  }),
  buildCase({
    id: 'content-calendar',
    slug: 'content-calendar',
    title: 'Content Calendar',
    description: '为内容团队准备的日历看板，支持选题规划、发布节奏和渠道状态的统一查看。',
    category: '内容工具',
    categorySlug: 'dashboard',
    tools: ['Claude Code'],
    tags: ['内容规划', '日历'],
    visualType: 'dashboard',
    publishedAt: '2026-06-03',
    viewCount: 612,
    likeCount: 33,
    submitterId: 'mia',
  }),
  buildCase({
    id: 'mini-crm',
    slug: 'mini-crm',
    title: 'Mini CRM',
    description: '轻量销售管理工具，聚焦客户分层、跟进记录和成交机会的快速浏览。',
    category: '客户管理',
    categorySlug: 'crm',
    tools: ['Cursor'],
    tags: ['客户管理', '销售'],
    visualType: 'crm',
    publishedAt: '2026-06-02',
    viewCount: 578,
    likeCount: 29,
    submitterId: 'david',
  }),
  buildCase({
    id: 'design-review-board',
    slug: 'design-review-board',
    title: 'Design Review Board',
    description: '用于收集设计反馈和整理修改建议的协作工具，适合复盘 AI 生成界面的质量判断。',
    category: 'SaaS 产品',
    categorySlug: 'saas',
    tools: ['Lovable'],
    tags: ['设计协作', '评审'],
    visualType: 'prompt',
    publishedAt: '2026-06-01',
    viewCount: 721,
    likeCount: 46,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'analytics-console',
    slug: 'analytics-console',
    title: 'Analytics Console',
    description: '围绕核心指标、异常状态和趋势摘要构建的数据控制台，强调信息层级和阅读效率。',
    category: '数据看板',
    categorySlug: 'dashboard',
    tools: ['Codex'],
    tags: ['数据分析', '控制台'],
    visualType: 'dashboard',
    publishedAt: '2026-05-30',
    viewCount: 1042,
    likeCount: 68,
    submitterId: 'david',
  }),
  buildCase({
    id: 'landing-page-kit',
    slug: 'landing-page-kit',
    title: 'Landing Page Kit',
    description: '把常见首屏、功能介绍和转化模块整理成可复用模板的官网搭建案例。',
    category: '官网',
    categorySlug: 'landing-page',
    tools: ['v0'],
    tags: ['官网', '模板'],
    visualType: 'landing',
    publishedAt: '2026-05-28',
    viewCount: 895,
    likeCount: 52,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'pixel-quest-game',
    title: 'Pixel Quest 小游戏',
    description: '一个轻量网页小游戏案例，展示角色状态、关卡入口和基础交互反馈的搭建方式。',
    category: '游戏',
    tools: ['Bolt'],
    tags: ['游戏', '交互'],
    visualType: 'landing',
    publishedAt: '2026-05-26',
    viewCount: 768,
    likeCount: 47,
    submitterId: 'mia',
  }),
  buildCase({
    id: 'soundflow-music',
    title: 'SoundFlow 音乐工具',
    description: '用于整理歌单、生成音乐灵感和记录创作片段的 AI 音乐产品原型。',
    category: '音乐',
    tools: ['Windsurf'],
    tags: ['音乐', '创作'],
    visualType: 'prompt',
    publishedAt: '2026-05-24',
    viewCount: 642,
    likeCount: 39,
    submitterId: 'lin',
  }),
  buildCase({
    id: 'coursekit-learning',
    title: 'CourseKit 学习平台',
    description: '面向知识创作者的课程页面，包含章节结构、学习进度和资料整理体验。',
    category: '教育',
    tools: ['GitHub Copilot'],
    tags: ['教育', '课程'],
    visualType: 'dashboard',
    publishedAt: '2026-05-22',
    viewCount: 812,
    likeCount: 58,
    submitterId: 'mia',
  }),
  buildCase({
    id: 'shopmate-store',
    title: 'ShopMate 商品页',
    description: '用于展示商品卖点、购买入口和信任信息的电商页面案例，适合学习转化设计。',
    category: '电商',
    tools: ['Replit'],
    tags: ['电商', '商品页'],
    visualType: 'landing',
    publishedAt: '2026-05-20',
    viewCount: 706,
    likeCount: 44,
    submitterId: 'david',
  }),
  buildCase({
    id: 'cursor-seo-dashboard',
    slug: 'cursor-seo-dashboard',
    title: 'Search Foundry SEO 看板',
    description: '基于 Cursor 构建的 SEO 与 LLM 检索可见度看板，适合学习指标组织和结果呈现。',
    category: 'Dashboard',
    categorySlug: 'dashboard',
    tools: ['Cursor'],
    tags: ['SEO', 'Dashboard', 'GitHub'],
    websiteUrl: 'https://search-foundry.github.io/dashboard-llm/',
    sourceType: '外部精选',
    sourceName: 'Cursor Community / GitHub',
    sourceUrl: 'https://github.com/Search-Foundry/dashboard-llm',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 1326,
    likeCount: 88,
    featured: true,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Search Foundry SEO 看板' }),
  }),
  buildCase({
    id: 'cursor-saas-mvp',
    slug: 'cursor-saas-mvp',
    title: 'Cursor SaaS MVP 工作流',
    description: 'Cursor 社区分享的 SaaS MVP 构建案例，适合学习从需求到可演示产品的快速迭代。',
    category: 'SaaS',
    categorySlug: 'saas',
    tools: ['Cursor'],
    tags: ['SaaS', 'MVP', 'Workflow'],
    websiteUrl: 'https://forum.cursor.com/t/built-a-full-saas-mvp-in-one-evening-with-cursor-claude-code-workflow-breakdown/156758',
    sourceType: '外部精选',
    sourceName: 'Cursor Community',
    sourceUrl: 'https://forum.cursor.com/t/built-a-full-saas-mvp-in-one-evening-with-cursor-claude-code-workflow-breakdown/156758',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 924,
    likeCount: 57,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Cursor SaaS MVP 工作流' }),
  }),
  buildCase({
    id: 'lovable-habit-tracker',
    slug: 'lovable-habit-tracker',
    title: 'Continuum 习惯追踪工具',
    description: 'Lovable 模板中的日常习惯追踪应用，适合学习目标、进度和复盘信息的组织方式。',
    category: 'SaaS',
    categorySlug: 'saas',
    tools: ['Lovable'],
    tags: ['Habit Tracker', 'SaaS', '习惯管理'],
    websiteUrl: 'https://lovable.dev/templates/apps/saas/continuum-daily-habit-tracker-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/saas/continuum-daily-habit-tracker-template',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 846,
    likeCount: 52,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Continuum 习惯追踪工具' }),
  }),
  buildCase({
    id: 'lovable-booking-tool',
    slug: 'lovable-booking-tool',
    title: 'Flux Desk 预约管理工具',
    description: 'Lovable 模板中的混合办公与会议室预约工具，适合学习资源状态和预订流程设计。',
    category: 'SaaS',
    categorySlug: 'saas',
    tools: ['Lovable'],
    tags: ['Booking', 'Workspace', 'SaaS'],
    websiteUrl: 'https://lovable.dev/templates/apps/saas/flux-hybrid-workplace-management-platform-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/saas/flux-hybrid-workplace-management-platform-template',
    copyrightNote: externalCopyrightNote,
    visualType: 'crm',
    publishedAt: '2026-06-15',
    viewCount: 1118,
    likeCount: 76,
    featured: true,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Flux Desk 预约管理工具' }),
  }),
  buildCase({
    id: 'bolt-internal-crm',
    slug: 'bolt-internal-crm',
    title: 'Bolt Internal CRM',
    description: 'Bolt 官方模板文章中的 CRM 方向案例，适合学习线索、客户状态和跟进任务的组织。',
    category: 'CRM',
    categorySlug: 'crm',
    tools: ['Bolt'],
    tags: ['CRM', 'Internal Tool', 'Sales'],
    websiteUrl: 'https://bolt.new/blog/top-5-bolt-new-templates-to-jumpstart-your-next-project',
    sourceType: '外部精选',
    sourceName: 'Bolt Templates',
    sourceUrl: 'https://bolt.new/blog/top-5-bolt-new-templates-to-jumpstart-your-next-project',
    copyrightNote: externalCopyrightNote,
    visualType: 'crm',
    publishedAt: '2026-06-15',
    viewCount: 1006,
    likeCount: 69,
    featured: true,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Bolt Internal CRM' }),
  }),
  buildCase({
    id: 'bolt-landing-page',
    slug: 'bolt-landing-page',
    title: 'Bolt Startup Landing Page',
    description: 'Bolt 官方模板文章中的创业公司官网案例，适合学习首屏卖点、证据和转化入口。',
    category: 'Landing Page',
    categorySlug: 'landing-page',
    tools: ['Bolt'],
    tags: ['Landing Page', 'Startup', 'Website'],
    websiteUrl: 'https://bolt.new/blog/top-5-bolt-new-templates-to-jumpstart-your-next-project',
    sourceType: '外部精选',
    sourceName: 'Bolt Templates',
    sourceUrl: 'https://bolt.new/blog/top-5-bolt-new-templates-to-jumpstart-your-next-project',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 782,
    likeCount: 43,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Bolt Startup Landing Page' }),
  }),
  buildCase({
    id: 'v0-customer-success-dashboard',
    slug: 'v0-customer-success-dashboard',
    title: 'v0 Customer Success 看板',
    description: 'v0 模板中的客户成功管理应用，适合学习客户健康度、任务状态和运营指标展示。',
    category: 'Dashboard',
    categorySlug: 'dashboard',
    tools: ['v0'],
    tags: ['Customer Success', 'Dashboard', '运营'],
    websiteUrl: 'https://v0-orbit-internal-app.vercel.app/',
    sourceType: '外部精选',
    sourceName: 'v0 Examples',
    sourceUrl: 'https://v0.app/templates/GjfM6W3LNhT',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 1194,
    likeCount: 82,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'v0 Customer Success 看板' }),
  }),
  buildCase({
    id: 'v0-salesops-dashboard',
    slug: 'v0-salesops-dashboard',
    title: 'SalesOps 销售运营看板',
    description: 'v0 官方模板中的销售运营仪表盘，覆盖收入跟踪、商机管理和团队绩效分析，适合学习业务指标型看板设计。',
    category: '数据看板',
    categorySlug: 'dashboard',
    tools: ['v0'],
    tags: ['销售运营', '数据看板', 'v0'],
    websiteUrl: 'https://v0.app/templates/salesops-dashboard-9q2Mfgu6cDi',
    sourceType: '外部精选',
    sourceName: 'v0 Templates',
    sourceUrl: 'https://v0.app/templates/salesops-dashboard-9q2Mfgu6cDi',
    screenshotUrl: 'https://gvsmhepiuiax2e6y.public.blob.vercel-storage.com/templates/assets/ezgif-464bbe623ade3f56-nNnxi4IMwxHh8nXLULPHLdglqOwBsk.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 1018,
    likeCount: 66,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: 'SalesOps Dashboard 以销售团队的日常决策为中心，把收入、商机、客户获取和团队表现放在同一张看板中。',
        image: 'https://gvsmhepiuiax2e6y.public.blob.vercel-storage.com/templates/assets/ezgif-464bbe623ade3f56-nNnxi4IMwxHh8nXLULPHLdglqOwBsk.webp',
        imageAlt: 'SalesOps 销售运营看板截图',
        points: ['关键指标集中呈现', '销售漏斗和趋势信息并列展示', '管理视角和执行视角兼顾'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页描述了收入跟踪、商机管理、团队绩效分析和销售趋势可视化，这些能力适合拆解成指标卡、图表和列表模块。',
        image: 'https://gvsmhepiuiax2e6y.public.blob.vercel-storage.com/templates/assets/Screenshot%202025-08-18%20at%2011.23.26%201-qinzAJXLXRGRNuOkMO6MzF2hVjAEau.jpg',
        imageAlt: 'SalesOps 销售运营看板界面预览',
        points: ['收入和增长趋势跟踪', '商机阶段和客户转化分析', '团队绩效可视化'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合练习销售类看板的需求拆分：先确定业务目标，再定义指标层级，最后用图表、列表和状态标签组织页面。',
        image: '',
        imageAlt: 'SalesOps UIcoding 案例拆解示意图',
        points: ['先明确销售角色的核心问题', '再按指标、趋势、任务拆模块', '最后控制看板的信息密度'],
      },
    ],
  }),
  buildCase({
    id: 'replit-agent-app-prototype',
    slug: 'replit-agent-app-prototype',
    title: 'Replit Agent App Prototype',
    description: 'Replit 官方客户案例中的 AI Agent 应用原型方向，适合学习从想法到可运行产品的过程。',
    category: 'SaaS',
    categorySlug: 'saas',
    tools: ['Replit'],
    tags: ['Agent', 'Prototype', 'SaaS'],
    websiteUrl: 'https://podnudge.com',
    sourceType: '外部精选',
    sourceName: 'Replit Showcase',
    sourceUrl: 'https://replit.com/usecases/customers',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 654,
    likeCount: 38,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: createExternalDetailSections({ title: 'Replit Agent App Prototype' }),
  }),
  buildCase({
    id: 'clipcraft-video-editor',
    slug: 'clipcraft-video-editor',
    title: 'ClipCraft 浏览器视频编辑器',
    description: 'Lovable 官方模板中的浏览器视频编辑 SaaS，适合学习视频工具的功能组织、试用转化和白标产品结构。',
    category: '内容工具',
    categorySlug: 'content-tool',
    tools: ['Lovable'],
    tags: ['视频编辑', 'SaaS', '内容工具'],
    websiteUrl: 'https://lovable.dev/templates/apps/saas/clipcraft-browser-based-video-editor-saas-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/saas/clipcraft-browser-based-video-editor-saas-template',
    screenshotUrl: 'https://assets.lovable.dev/templates/clipcraft-browser-based-video-editor-saas-template-screenshot.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 734,
    likeCount: 49,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: 'ClipCraft 把视频编辑、导出格式、白标能力和试用转化放在同一条产品路径里，适合拆解内容工具的 SaaS 信息架构。',
        image: 'https://assets.lovable.dev/templates/clipcraft-browser-based-video-editor-saas-template-screenshot.webp',
        imageAlt: 'ClipCraft 浏览器视频编辑器截图',
        points: ['首屏说明清楚产品定位', '编辑能力和商业化能力并列呈现', '从试用到注册的路径自然'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页强调浏览器端视频处理、社交媒体比例预设、白标品牌和访客试用模式，这些都是内容工具转化设计的关键点。',
        image: 'https://assets.lovable.dev/templates/previews/clipcraft-browser-based-video-editor-saas-template-preview.webp',
        imageAlt: 'ClipCraft 功能预览截图',
        points: ['浏览器端剪辑和导出', '9:16、1:1、16:9 等社交格式预设', '白标品牌和水印能力'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合练习把复杂工具拆成清晰模块：先定义用户任务，再组织编辑区、格式预设、导出和账号转化。',
        image: '',
        imageAlt: 'ClipCraft UIcoding 案例拆解示意图',
        points: ['先拆核心编辑任务', '再规划导出和格式转换流程', '最后补齐试用转化和白标细节'],
      },
    ],
  }),
  buildCase({
    id: 'signaturecrafter-email-signature',
    slug: 'signaturecrafter-email-signature',
    title: 'SignatureCrafter 邮件签名工具',
    description: 'Lovable 官方模板中的邮件签名与二维码生成工具，适合学习轻量内容工具的模板选择、预览和导出流程。',
    category: '内容工具',
    categorySlug: 'content-tool',
    tools: ['Lovable'],
    tags: ['邮件签名', '二维码', '内容工具'],
    websiteUrl: 'https://lovable.dev/templates/apps/saas/signaturecrafter-email-signature-qr-code-generator-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/saas/signaturecrafter-email-signature-qr-code-generator-template',
    screenshotUrl: 'https://assets.lovable.dev/templates/signaturecrafter-email-signature-qr-code-generator-template-screenshot.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 692,
    likeCount: 45,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: 'SignatureCrafter 围绕“快速生成专业邮件签名”组织信息，把模板选择、资料填写、二维码和导出路径放在清晰流程中。',
        image: 'https://assets.lovable.dev/templates/signaturecrafter-email-signature-qr-code-generator-template-screenshot.webp',
        imageAlt: 'SignatureCrafter 邮件签名工具截图',
        points: ['目标任务非常单一', '模板与预览形成即时反馈', '导出场景直接对应常用邮箱客户端'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页介绍了六种签名模板、二维码生成，以及面向 Gmail、Outlook 和 Apple Mail 的导出能力。',
        image: 'https://assets.lovable.dev/templates/previews/signaturecrafter-email-signature-qr-code-generator-template-preview.webp',
        imageAlt: 'SignatureCrafter 功能预览截图',
        points: ['多模板签名生成', '二维码信息承载', '面向邮箱客户端的导出'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合学习轻量工具的产品化方式：少做复杂导航，把输入、预览和结果导出放在同一条短路径里。',
        image: '',
        imageAlt: 'SignatureCrafter UIcoding 案例拆解示意图',
        points: ['先聚焦一个高频小任务', '再设计即时预览反馈', '最后补齐导出和使用场景'],
      },
    ],
  }),
  buildCase({
    id: 'scout-startup-funding-tracker',
    slug: 'scout-startup-funding-tracker',
    title: 'Scout 创业融资情报平台',
    description: 'Lovable 官方模板中的创业融资追踪平台，适合学习资讯聚合、筛选检索和研究后台的产品结构。',
    category: '数据看板',
    categorySlug: 'dashboard',
    tools: ['Lovable'],
    tags: ['融资追踪', '情报平台', '数据看板'],
    websiteUrl: 'https://lovable.dev/templates/apps/saas/scout-startup-funding-tracker-news-platform-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/saas/scout-startup-funding-tracker-news-platform-template',
    screenshotUrl: 'https://assets.lovable.dev/templates/scout-startup-funding-tracker-news-platform-template-screenshot.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 878,
    likeCount: 61,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: 'Scout 围绕创业公司融资信息组织页面，把融资轮次、行业分类、新闻内容和研究管理放在一套情报平台结构里。',
        image: 'https://assets.lovable.dev/templates/scout-startup-funding-tracker-news-platform-template-screenshot.webp',
        imageAlt: 'Scout 创业融资情报平台截图',
        points: ['融资信息作为核心内容', '筛选条件帮助快速定位', '后台管理支撑研究维护'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页强调融资轮次追踪、按阶段和类别筛选，以及内置后台管理，适合拆解成列表、筛选器和管理模块。',
        image: 'https://assets.lovable.dev/templates/previews/scout-startup-funding-tracker-news-platform-template-preview.webp',
        imageAlt: 'Scout 创业融资情报平台功能预览',
        points: ['融资轮次和新闻追踪', '按阶段与类别筛选', '内置研究管理后台'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合学习信息型产品的构建方式：先定义内容字段，再设计筛选维度，最后补齐管理后台和更新流程。',
        image: '',
        imageAlt: 'Scout UIcoding 案例拆解示意图',
        points: ['先抽象内容数据结构', '再设计筛选和排序入口', '最后规划编辑和维护流程'],
      },
    ],
  }),
  buildCase({
    id: 'expensedesk-approval-tool',
    slug: 'expensedesk-approval-tool',
    title: 'ExpenseDesk 报销审批工具',
    description: 'Lovable 官方模板中的费用报销与审批工具，适合学习表单提交、审批流、审计记录和支出分析的组织方式。',
    category: 'SaaS 产品',
    categorySlug: 'saas',
    tools: ['Lovable'],
    tags: ['报销审批', '内部工具', 'SaaS'],
    websiteUrl: 'https://lovable.dev/templates/apps/internal-tools/expensedesk-expense-reporting-approval-tool-template',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/apps/internal-tools/expensedesk-expense-reporting-approval-tool-template',
    screenshotUrl: 'https://storage.googleapis.com/lovable-assets/templates/expense_deck.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'dashboard',
    publishedAt: '2026-06-15',
    viewCount: 814,
    likeCount: 54,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: 'ExpenseDesk 围绕企业费用报销的完整流程组织页面，从员工提交到管理者审批，再到支出分析和审计记录。',
        image: 'https://storage.googleapis.com/lovable-assets/templates/expense_deck.webp',
        imageAlt: 'ExpenseDesk 报销审批工具截图',
        points: ['提交和审批路径清楚', '状态与责任人明确', '分析看板辅助管理判断'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页介绍了票据上传、费用分类、多步骤审批、完整审计轨迹、AI 助手和支出分析等能力。',
        image: 'https://storage.googleapis.com/lovable-assets/templates/expense_deck.webp',
        imageAlt: 'ExpenseDesk 报销审批工具功能预览',
        points: ['费用申请和票据上传', '多步骤审批工作流', '审计记录与支出分析'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合学习内部工具如何组织复杂状态：先设计表单字段，再拆审批节点，最后补充记录、权限和数据分析。',
        image: '',
        imageAlt: 'ExpenseDesk UIcoding 案例拆解示意图',
        points: ['先拆清楚业务流程', '再定义不同角色的操作入口', '最后用状态和记录降低沟通成本'],
      },
    ],
  }),
  buildCase({
    id: 'lovable-ecommerce-store',
    slug: 'lovable-ecommerce-store',
    title: 'Lovable 电商商店模板',
    description: 'Lovable 官方电商网站模板，覆盖商品页、购物车和响应式布局，适合学习商品转化型页面结构。',
    category: '电商',
    categorySlug: 'ecommerce',
    tools: ['Lovable'],
    tags: ['电商', '商品页', '购物车'],
    websiteUrl: 'https://lovable.dev/templates/websites/ecommerce/ecommerce-store-1',
    sourceType: '外部精选',
    sourceName: 'Lovable Templates',
    sourceUrl: 'https://lovable.dev/templates/websites/ecommerce/ecommerce-store-1',
    screenshotUrl: 'https://assets.lovable.dev/templates/ecommerce-store-1-screenshot.webp',
    copyrightNote: externalCopyrightNote,
    visualType: 'landing',
    publishedAt: '2026-06-15',
    viewCount: 768,
    likeCount: 51,
    featured: false,
    submitterId: 'uicodingEditor',
    detailSections: [
      {
        id: 'overview',
        title: '作品结构',
        description: '这个电商模板围绕商品展示和购买转化组织页面，把商品信息、购买入口、购物车和响应式浏览体验作为核心。',
        image: 'https://assets.lovable.dev/templates/ecommerce-store-1-screenshot.webp',
        imageAlt: 'Lovable 电商商店模板截图',
        points: ['商品信息前置', '购买路径短而清楚', '移动端和桌面端都能浏览'],
      },
      {
        id: 'features',
        title: '核心功能',
        description: '来源页强调清晰的商品页面、购物车功能和可定制响应式设计，适合拆解电商页面的基础转化模块。',
        image: 'https://assets.lovable.dev/templates/ecommerce-store-1-screenshot.webp',
        imageAlt: 'Lovable 电商商店模板功能预览',
        points: ['商品详情展示', '购物车与购买入口', '响应式页面布局'],
      },
      {
        id: 'uicoding-review',
        title: 'UIcoding 拆解',
        description: '这个案例适合练习电商页面的信息优先级：先说明产品价值，再组织购买动作，最后补充信任信息和适配细节。',
        image: '',
        imageAlt: 'Lovable 电商商店模板 UIcoding 拆解示意图',
        points: ['先确定商品卖点', '再设计购买和购物车路径', '最后检查移动端转化体验'],
      },
    ],
  }),
];

export const homeFeaturedIds = [
  'flowpilot-dashboard',
  'prompt-studio',
  'founder-crm',
  'launchkit',
  'ai-resume-builder',
  'saas-pricing-page',
  'taskflow-project',
  'content-calendar',
];

export const heroRecommendation = {
  eyebrow: '今日推荐',
  ...cases[0],
  description:
    '一个使用 AI 辅助完成的运营数据看板，包含指标概览、筛选状态和趋势复盘。',
};

export const lessonAudienceFilters = [
  '全部角色',
  '设计师',
  '产品经理',
  '独立开发者',
];

export const lessonToolFilters = [
  '全部工具',
  'Codex',
  'Cursor',
  'Claude Code',
  'v0',
  '通用',
];

export const lessonTopicFilters = [
  '全部主题',
  'Prompt',
  'UI Design',
  'Workflow',
  'Agent',
  '上线部署',
];

export const learningPathSteps = [
  '理解 AI Coding 工作流',
  '学会描述产品需求',
  '拆解优秀界面和组件',
  '使用 Codex / Cursor 构建项目',
  '调试、优化并上线',
];

export const lessons = [
  {
    "id": "uicoding-skill-coding-process",
    "title": "用 Codex + Impeccable 做 UIcoding.ai：从搭页面到设计审查",
    "originalTitle": "",
    "description": "记录 UIcoding.ai 的真实搭建过程：Codex 负责快速实现页面，Impeccable 负责设计审查和视觉质量把关。",
    "sourceType": "站内原创",
    "sourceName": "Uicoding.ai",
    "sourceUrl": "",
    "author": "传庆",
    "license": "原创内容",
    "translationMode": "original",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "8 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex",
      "Impeccable",
      "设计审查"
    ],
    "href": "/learn/uicoding-skill-coding-process",
    "publishedAt": "2026-06-16",
    "viewCount": 640,
    "likeCount": 52,
    "featured": true,
    "external": false,
    "keyTakeaways": [
      "Codex 负责实现页面",
      "Impeccable 负责设计审查",
      "每轮只修最重要的问题"
    ]
  },
  {
    "id": "knowlens-codex-2b-token-tips",
    "title": "20 亿 Token 后，我用 Codex 开发 KnowLens.ai 的 8 个技巧",
    "originalTitle": "",
    "description": "记录用 Codex 开发 KnowLens.ai 的真实经验：从任务拆分、避免重构，到上线和支付链路前的工作流反思。",
    "sourceType": "站内原创",
    "sourceName": "Uicoding.ai",
    "sourceUrl": "",
    "author": "传庆",
    "license": "原创内容",
    "translationMode": "original",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "10 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex",
      "真实经验",
      "工作流"
    ],
    "href": "/learn/knowlens-codex-2b-token-tips",
    "publishedAt": "2026-06-16",
    "viewCount": 520,
    "likeCount": 38,
    "featured": true,
    "external": false,
    "keyTakeaways": [
      "不要把需求一次性丢给 Codex",
      "先设计产品工作流再写代码",
      "从任务拆分减少返工和重构"
    ]
  },
  {
    "id": "codex-quickstart-first-task",
    "title": "Codex CLI 官方入门：安装、登录和第一次运行",
    "originalTitle": "openai/codex README · Quickstart",
    "description": "基于 openai/codex 官方 README 和 OpenAI Developers CLI 文档整理，逐步理解 Codex CLI 是什么、在哪里运行、怎么安装、怎么登录和如何完成第一次安全尝试。",
    "sourceType": "开源文档",
    "sourceName": "openai/codex GitHub README",
    "sourceUrl": "https://github.com/openai/codex#quickstart",
    "author": "OpenAI",
    "license": "Apache-2.0",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "18 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex CLI",
      "官方入门",
      "安装登录"
    ],
    "href": "/learn/codex-quickstart-first-task",
    "image": "/learn-covers/codex-quickstart.svg",
    "imageAlt": "Codex CLI 官方入门教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 874,
    "likeCount": 61,
    "featured": true,
    "external": true,
    "keyTakeaways": [
      "理解 Codex CLI 的使用入口",
      "按系统选择安装方式",
      "完成登录并做第一次安全尝试"
    ]
  },
  {
    "id": "codex-cli-basic-operations",
    "title": "Codex CLI 基础操作：从交互模式到第一个可验证修改",
    "originalTitle": "Codex CLI features",
    "description": "基于 OpenAI 官方 CLI 功能文档整理，学习如何在项目目录里启动 Codex、描述任务、检查 diff 并完成构建验证。",
    "sourceType": "官方文档",
    "sourceName": "OpenAI Developers",
    "sourceUrl": "https://developers.openai.com/codex/cli/features",
    "author": "OpenAI",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "11 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex CLI",
      "终端",
      "可验证修改"
    ],
    "href": "/learn/codex-cli-basic-operations",
    "image": "/learn-covers/codex-cli-basics.svg",
    "imageAlt": "Codex CLI 基础操作教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 766,
    "likeCount": 49,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "在项目目录启动 Codex",
      "用小任务控制修改范围",
      "通过 diff 和 build 验证结果"
    ]
  },
  {
    "id": "codex-safety-sandbox-approvals",
    "title": "Codex 安全使用入门：沙盒、审批和 Git 检查点",
    "originalTitle": "Agent approvals and security",
    "description": "基于 OpenAI 官方安全和沙盒资料整理，帮助新手理解审批、沙盒、权限边界和修改前后的 Git 检查习惯。",
    "sourceType": "官方文档",
    "sourceName": "OpenAI Developers",
    "sourceUrl": "https://developers.openai.com/codex/agent-approvals-security",
    "author": "OpenAI",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "13 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "安全",
      "审批",
      "Sandbox"
    ],
    "href": "/learn/codex-safety-sandbox-approvals",
    "image": "/learn-covers/codex-safety.svg",
    "imageAlt": "Codex 安全使用教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 702,
    "likeCount": 44,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "理解沙盒和审批",
      "谨慎授权高风险操作",
      "用 Git 检查每轮修改"
    ]
  },
  {
    "id": "codex-prompting-basics",
    "title": "Codex 提示词入门：如何把需求讲清楚",
    "originalTitle": "Prompting Codex",
    "description": "基于 OpenAI 官方 Codex 提示词资料整理，学习如何写清目标、范围、约束、验收标准和停止条件。",
    "sourceType": "官方文档",
    "sourceName": "OpenAI Developers",
    "sourceUrl": "https://developers.openai.com/codex/prompting",
    "author": "OpenAI",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "14 分钟",
    "category": "Prompt",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Prompt",
      "需求描述",
      "验收标准"
    ],
    "href": "/learn/codex-prompting-basics",
    "image": "/learn-covers/codex-prompting.svg",
    "imageAlt": "Codex 提示词入门教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 914,
    "likeCount": 73,
    "featured": true,
    "external": true,
    "keyTakeaways": [
      "把模糊需求改成清晰任务",
      "明确允许修改的范围",
      "写出可验证的完成标准"
    ]
  },
  {
    "id": "codex-best-practices-plan-first",
    "title": "Codex 最佳实践：先计划，再写代码",
    "originalTitle": "Codex best practices",
    "description": "基于 OpenAI 官方最佳实践整理，学习如何先让 Codex 规划、拆解任务、沉淀项目规则，再逐步执行修改。",
    "sourceType": "官方文档",
    "sourceName": "OpenAI Developers",
    "sourceUrl": "https://developers.openai.com/codex/learn/best-practices",
    "author": "OpenAI",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "15 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Plan mode",
      "AGENTS.md",
      "工作流"
    ],
    "href": "/learn/codex-best-practices-plan-first",
    "image": "/learn-covers/codex-best-practices.svg",
    "imageAlt": "Codex 最佳实践教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 870,
    "likeCount": 66,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "先讨论计划再改代码",
      "把项目约束写进规则",
      "每轮任务后做验收"
    ]
  },
  {
    "id": "claude-code-beginner-first-task",
    "title": "Claude Code 新手入门：安装并完成第一个任务",
    "originalTitle": "Terminal guide for new users",
    "description": "基于 Claude Code 官方新手终端指南整理，带你从安装、进入项目、提出第一个任务到检查修改结果。",
    "sourceType": "官方文档",
    "sourceName": "Claude Code Docs",
    "sourceUrl": "https://code.claude.com/docs/en/terminal-guide",
    "author": "Anthropic",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "12 分钟",
    "category": "Agent",
    "tools": [
      "Claude Code"
    ],
    "tags": [
      "Claude Code",
      "新手教程",
      "终端"
    ],
    "href": "/learn/claude-code-beginner-first-task",
    "image": "/learn-covers/claude-code-beginner.svg",
    "imageAlt": "Claude Code 官方新手终端指南封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 724,
    "likeCount": 51,
    "featured": true,
    "external": true,
    "keyTakeaways": [
      "完成 Claude Code 安装",
      "进入项目并启动 Claude",
      "提出第一个可验证任务"
    ]
  },
  {
    "id": "claude-code-quickstart-zero-basic",
    "title": "Claude Code Quickstart：零基础完成第一个小修改",
    "originalTitle": "Claude Code quickstart",
    "description": "基于 Anthropic 官方 Quickstart 整理，从终端、项目目录和安装开始，带零基础用户完成一次可验证的小修改。",
    "sourceType": "官方文档",
    "sourceName": "Claude Code Docs",
    "sourceUrl": "https://code.claude.com/docs/en/quickstart",
    "author": "Anthropic",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "16 分钟",
    "category": "Agent",
    "tools": [
      "Claude Code"
    ],
    "tags": [
      "Claude Code",
      "Quickstart",
      "零基础"
    ],
    "href": "/learn/claude-code-quickstart-zero-basic",
    "image": "/learn-covers/claude-code-quickstart.svg",
    "imageAlt": "Claude Code Quickstart 新手教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 638,
    "likeCount": 42,
    "featured": true,
    "external": true,
    "keyTakeaways": [
      "理解终端和项目目录",
      "安装并启动 Claude Code",
      "完成一次小范围修改和验证"
    ]
  },
  {
    "id": "claude-code-common-workflows-beginner",
    "title": "Claude Code 常用工作流：读懂项目、修问题、做验证",
    "originalTitle": "Claude Code common workflows",
    "description": "基于 Anthropic 官方 Common workflows 整理，带新手学习如何让 Claude Code 先理解项目，再安全地修问题和验证结果。",
    "sourceType": "官方文档",
    "sourceName": "Claude Code Docs",
    "sourceUrl": "https://docs.anthropic.com/en/docs/claude-code/common-workflows",
    "author": "Anthropic",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "15 分钟",
    "category": "Agent",
    "tools": [
      "Claude Code"
    ],
    "tags": [
      "Claude Code",
      "工作流",
      "新手教程"
    ],
    "href": "/learn/claude-code-common-workflows-beginner",
    "image": "/learn-covers/claude-code-workflows.svg",
    "imageAlt": "Claude Code 常用工作流教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 604,
    "likeCount": 39,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "让 Claude 先读懂项目",
      "从小问题开始修改",
      "用构建和页面检查验证结果"
    ]
  },
  {
    "id": "claude-code-memory-project-rules",
    "title": "Claude Code 记忆入门：让它记住项目规则",
    "originalTitle": "How Claude remembers your project",
    "description": "基于 Anthropic 官方 Memory 文档整理，帮助新手理解 Claude Code 如何记住项目上下文，以及如何沉淀规则减少重复解释。",
    "sourceType": "官方文档",
    "sourceName": "Claude Code Docs",
    "sourceUrl": "https://docs.anthropic.com/en/docs/claude-code/memory",
    "author": "Anthropic",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "14 分钟",
    "category": "Agent",
    "tools": [
      "Claude Code"
    ],
    "tags": [
      "Claude Code",
      "Memory",
      "项目规则"
    ],
    "href": "/learn/claude-code-memory-project-rules",
    "image": "/learn-covers/claude-code-memory.svg",
    "imageAlt": "Claude Code 记忆和项目规则教程封面图",
    "publishedAt": "2026-06-16",
    "viewCount": 582,
    "likeCount": 36,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "理解项目记忆",
      "沉淀重复规则",
      "避免每次重新解释上下文"
    ]
  },
  {
    "id": "datacamp-codex-cli-beginner",
    "title": "Codex CLI 新手入门：从安装到生成页面",
    "originalTitle": "OpenAI Codex CLI Tutorial",
    "description": "基于 DataCamp 新手教程整理，学习安装 Codex CLI、使用图片输入生成网页，并理解审批模式。",
    "sourceType": "开发者教程",
    "sourceName": "DataCamp",
    "sourceUrl": "https://www.datacamp.com/tutorial/open-ai-codex-cli-tutorial",
    "author": "Abid Ali Awan",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-16",
    "audience": "零基础学习者",
    "duration": "9 分钟",
    "category": "Workflow",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex CLI",
      "新手教程",
      "Workflow"
    ],
    "href": "/learn/datacamp-codex-cli-beginner",
    "image": "/learn-covers/codex-cli-basics.svg",
    "imageAlt": "Codex CLI 教程封面界面示意图",
    "publishedAt": "2026-06-16",
    "viewCount": 692,
    "likeCount": 46,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "安装并启动 Codex CLI",
      "理解审批模式",
      "用截图作为输入生成网页原型"
    ]
  },
  {
    "id": "codex-usage-practices",
    "title": "Codex 使用实践：如何把任务交代清楚",
    "originalTitle": "Prompting Codex",
    "description": "基于 OpenAI Codex 官方提示词资料整理，学习如何限定范围、说明目标并让 Agent 稳定修改代码。",
    "sourceType": "官方文档",
    "sourceName": "OpenAI Developers",
    "sourceUrl": "https://developers.openai.com/codex/prompting",
    "author": "OpenAI",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "独立开发者",
    "duration": "13 分钟",
    "category": "Prompt",
    "tools": [
      "Codex"
    ],
    "tags": [
      "Codex",
      "Prompt",
      "Agent"
    ],
    "href": "/learn/codex-usage-practices",
    "publishedAt": "2026-06-15",
    "viewCount": 1186,
    "likeCount": 82,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "先说明目标和验收标准",
      "限定要修改的文件和范围",
      "要求 Agent 运行构建或测试验证结果"
    ]
  },
  {
    "id": "cursor-agent-workflow",
    "title": "Cursor Agent 工作流：从需求到多文件修改",
    "originalTitle": "Cursor Agent Documentation",
    "description": "基于 Cursor 官方 Agent 文档整理，理解如何让 Agent 在项目上下文中规划、编辑和验证多文件任务。",
    "sourceType": "官方文档",
    "sourceName": "Cursor Docs",
    "sourceUrl": "https://docs.cursor.com/agent/overview",
    "author": "Cursor",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "独立开发者",
    "duration": "12 分钟",
    "category": "Workflow",
    "tools": [
      "Cursor"
    ],
    "tags": [
      "Cursor",
      "Agent",
      "Workflow"
    ],
    "href": "/learn/cursor-agent-workflow",
    "publishedAt": "2026-06-15",
    "viewCount": 936,
    "likeCount": 63,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "把大任务拆成可审查步骤",
      "让 Agent 利用项目上下文",
      "每轮修改后检查 diff 和运行结果"
    ]
  },
  {
    "id": "cursor-rules-project-standards",
    "title": "Cursor Rules 项目规范：让 AI 按你的方式写代码",
    "originalTitle": "Cursor Rules Documentation",
    "description": "基于 Cursor Rules 文档整理，学习如何沉淀项目约束、组件规范和团队协作规则。",
    "sourceType": "官方文档",
    "sourceName": "Cursor Docs",
    "sourceUrl": "https://docs.cursor.com/context/rules",
    "author": "Cursor",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "设计师",
    "duration": "10 分钟",
    "category": "Workflow",
    "tools": [
      "Cursor"
    ],
    "tags": [
      "Cursor",
      "Rules",
      "Workflow"
    ],
    "href": "/learn/cursor-rules-project-standards",
    "publishedAt": "2026-06-15",
    "viewCount": 804,
    "likeCount": 51,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "把设计系统和代码约束写进规则",
      "区分全局规则和项目规则",
      "用规则减少重复解释和返工"
    ]
  },
  {
    "id": "claude-code-best-practices",
    "title": "Claude Code 最佳实践：用 Agent 处理真实代码库",
    "originalTitle": "Claude Code: Best practices for agentic coding",
    "description": "基于 Anthropic 官方工程博客整理，学习如何配置上下文、拆解任务并安全地使用命令行 Agent。",
    "sourceType": "官方博客",
    "sourceName": "Anthropic Engineering",
    "sourceUrl": "https://www.anthropic.com/engineering/claude-code-best-practices",
    "author": "Anthropic",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "独立开发者",
    "duration": "15 分钟",
    "category": "Agent",
    "tools": [
      "Claude Code"
    ],
    "tags": [
      "Claude Code",
      "Agent",
      "Best Practices"
    ],
    "href": "/learn/claude-code-best-practices",
    "publishedAt": "2026-06-15",
    "viewCount": 1240,
    "likeCount": 95,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "先建立项目上下文",
      "让 Agent 小步执行并确认结果",
      "保留人工审查和权限控制"
    ]
  },
  {
    "id": "v0-ui-prompting-method",
    "title": "v0 界面生成方法：从页面意图到组件提示词",
    "originalTitle": "v0 Documentation",
    "description": "基于 v0 官方文档整理，学习如何描述页面结构、视觉风格、交互状态和可复用组件。",
    "sourceType": "官方文档",
    "sourceName": "v0 Docs",
    "sourceUrl": "https://v0.app/docs",
    "author": "Vercel",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "产品经理",
    "duration": "11 分钟",
    "category": "UI Design",
    "tools": [
      "v0"
    ],
    "tags": [
      "v0",
      "UI Design",
      "Prompt"
    ],
    "href": "/learn/v0-ui-prompting-method",
    "publishedAt": "2026-06-15",
    "viewCount": 874,
    "likeCount": 59,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "先定义页面目标和用户任务",
      "明确组件、布局和响应式要求",
      "把生成结果继续人工打磨"
    ]
  },
  {
    "id": "context-engineering-coding-agents",
    "title": "Coding Agent 的上下文工程：让 AI 看见正确的信息",
    "originalTitle": "Context engineering for coding agents",
    "description": "基于 Martin Fowler 网站的开发者文章整理，理解为什么上下文比单次提示词更影响 Agent 结果。",
    "sourceType": "开发者文章",
    "sourceName": "Martin Fowler",
    "sourceUrl": "https://martinfowler.com/articles/exploring-gen-ai/context-engineering-coding-agents.html",
    "author": "Martin Fowler / Thoughtworks",
    "license": "未确认",
    "translationMode": "guidedTranslation",
    "collectedAt": "2026-06-15",
    "audience": "独立开发者",
    "duration": "16 分钟",
    "category": "Agent",
    "tools": [
      "通用"
    ],
    "tags": [
      "Context Engineering",
      "Agent",
      "Workflow"
    ],
    "href": "/learn/context-engineering-coding-agents",
    "publishedAt": "2026-06-15",
    "viewCount": 1072,
    "likeCount": 87,
    "featured": false,
    "external": true,
    "keyTakeaways": [
      "上下文要包含目标、约束和代码线索",
      "减少无关信息能提升输出稳定性",
      "用文件、规则和反馈循环管理上下文"
    ]
  }
];

export const learningResources = lessons.filter((lesson) => lesson.featured);

export const toolCategoryFilters = [
  '全部',
  'AI IDE',
  'Coding Agent',
  'App Builder',
  'Code Assistant',
  'Open Source',
];

export const tools = [
  {
    id: 'codex',
    slug: 'codex',
    name: 'Codex',
    company: 'OpenAI',
    description: 'OpenAI 的编程 Agent，面向真实代码库执行任务拆解、文件修改和构建验证，适合把需求推进成可审查的代码改动。',
    category: 'Coding Agent',
    tags: ['代码修改', '项目协作', '构建验证'],
    href: '/tools/codex',
    officialUrl: 'https://openai.com/codex/',
    pricing: 'ChatGPT Plus、Pro、Business、Edu 和 Enterprise 计划包含 Codex；具体额度随计划变化。',
    bestFor: ['在真实代码库中拆解任务和修改文件', '让 Agent 在云端后台处理多个任务', '理解陌生项目、修 bug 和跑构建验证', '把一次需求拆成可审查的代码改动'],
    coreAdvantages: ['能读取、编辑并运行代码，适合完整工程任务。', '支持云端后台执行，可以并行处理多个开发任务。', '有 CLI、IDE、Web 和桌面形态，适合不同开发习惯。', '适合把修改和验证过程沉淀为可审查结果。'],
    limitations: ['需要清楚约束任务范围，否则容易产生过大的改动。', '复杂产品判断仍需要人工审查交互、业务逻辑和边界条件。', '可用额度和功能形态会随 OpenAI 计划调整。'],
    benchmarks: [],
    userReviews: [
      {
        summary: '公开讨论普遍把 Codex 视为更接近“软件工程代理”的工具，而不是单纯代码补全。',
        sentiment: '正面',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/singularity/comments/1ko3mxq/openai_introducing_codex_software_engineering/',
      },
    ],
    sources: [
      { sourceName: 'OpenAI Codex Web Docs', url: 'https://developers.openai.com/codex/cloud' },
      { sourceName: 'OpenAI Codex App Docs', url: 'https://developers.openai.com/codex/app' },
      { sourceName: 'OpenAI Codex GitHub', url: 'https://github.com/openai/codex' },
    ],
  },
  {
    id: 'cursor',
    slug: 'cursor',
    name: 'Cursor',
    company: 'Anysphere',
    description: 'Anysphere 的 AI 代码编辑器，擅长理解项目上下文、补全代码和多文件修改，适合日常开发中的快速迭代。',
    category: 'AI IDE',
    tags: ['编辑器', '上下文', '快速迭代'],
    href: '/tools/cursor',
    officialUrl: 'https://cursor.com',
    pricing: 'Free / Paid；Pro 计划按月订阅，包含更高 Agent 限额和前沿模型额度。',
    bestFor: ['在编辑器里快速理解项目上下文', '小步修改组件、样式和业务逻辑', '通过 Agent 模式处理多文件任务', '日常补全、重构和代码解释'],
    coreAdvantages: ['编辑器体验接近传统 IDE，上手成本较低。', 'Agent、Rules、MCP、Skills 等能力适合建立团队工作流。', '适合频繁的小步修改和快速验证。', '能结合项目上下文生成更贴近当前代码的修改建议。'],
    limitations: ['复杂任务仍需要用户拆分步骤并检查输出。', '高频使用前沿模型时成本和额度需要关注。', '对大型重构的结果需要配合测试和代码审查。'],
    benchmarks: [],
    userReviews: [
      {
        summary: '不少用户认可 Cursor 的编辑器内上下文体验，但也会讨论高级请求额度和计费方式。',
        sentiment: '中性',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/cursor/comments/1j12qxk/new_to_cursor_ai_and_i_dont_understand_the/',
      },
      {
        summary: '独立使用体验文章通常认为 Cursor 适合深度代码上下文和多文件编辑，但价值取决于使用频率。',
        sentiment: '中性',
        sourceName: 'Medium',
        url: 'https://medium.com/realworld-ai-use-cases/cursor-ai-pricing-is-it-worth-it-a-deep-breakdown-of-my-past-month-06d5b7f51eac',
      },
    ],
    sources: [
      { sourceName: 'Cursor Docs', url: 'https://cursor.com/docs' },
      { sourceName: 'Cursor Pricing', url: 'https://cursor.com/pricing' },
      { sourceName: 'Cursor Models and Pricing Docs', url: 'https://cursor.com/docs/models-and-pricing' },
    ],
  },
  {
    id: 'claude-code',
    slug: 'claude-code',
    name: 'Claude Code',
    company: 'Anthropic',
    description: 'Anthropic 的编程 Agent，主打终端和 IDE 工作流，擅长长上下文代码理解、复杂重构和跨文件协作修改。',
    category: 'Coding Agent',
    tags: ['长上下文', '重构', '终端'],
    href: '/tools/claude-code',
    officialUrl: 'https://claude.com/product/claude-code',
    pricing: 'Free trial / Paid；可通过 Claude 计划或 API 计费使用，具体取决于接口和模型。',
    bestFor: ['终端或 IDE 内完成代码库问答', '跨文件重构和复杂问题定位', '解释历史代码和生成修改计划', '在 CI、Slack 或 Web 中处理工程任务'],
    coreAdvantages: ['面向代码库工作流设计，可以理解文件关系和任务上下文。', '支持终端、Web、桌面、VS Code、JetBrains、Slack 和 CI/CD 等入口。', '执行修改或命令前会请求权限，适合保持人工控制。', '适合长上下文分析和复杂代码解释。'],
    limitations: ['复杂重构仍需要测试覆盖和人工 review。', 'API 模式下成本随模型和用量变化较大。', '终端式工作流对零基础用户有一定学习门槛。'],
    benchmarks: [],
    userReviews: [
      {
        summary: 'GitHub 介绍强调它能通过自然语言处理 routine tasks、代码解释和 git 工作流，社区讨论集中在文档和工作流实践。',
        sentiment: '正面',
        sourceName: 'GitHub',
        url: 'https://github.com/anthropics/claude-code',
      },
    ],
    sources: [
      { sourceName: 'Claude Code Official', url: 'https://code.claude.com/' },
      { sourceName: 'Claude Code Quickstart', url: 'https://code.claude.com/docs/en/quickstart' },
      { sourceName: 'Claude Code GitHub', url: 'https://github.com/anthropics/claude-code' },
    ],
  },
  {
    id: 'github-copilot',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    company: 'GitHub / Microsoft',
    description: 'GitHub 和 Microsoft 的 AI 编程助手，深度集成 GitHub 与主流 IDE，适合代码补全、解释和轻量修改。',
    category: 'Code Assistant',
    tags: ['补全', 'IDE', 'GitHub'],
    href: '/tools/github-copilot',
    officialUrl: 'https://github.com/features/copilot',
    pricing: 'Free / Paid；个人、团队和企业有不同计划，部分计划包含月度 AI Credits。',
    bestFor: ['在 IDE 中获得代码补全和解释', 'GitHub 工作流中的 PR、Issue 和代码理解', '轻量代码修改和日常辅助开发', '团队使用统一的代码助手能力'],
    coreAdvantages: ['深度集成 GitHub 和主流 IDE，适合现有开发团队。', '提供 Free、Pro、Business、Enterprise 等不同计划。', '适合补全、代码解释、测试生成和轻量对话式修改。', '企业场景中有更完善的权限、策略和管理能力。'],
    limitations: ['复杂 Agent 工作流的额度和计费需要提前理解。', '生成代码质量仍依赖上下文和开发者审查。', '企业使用需要关注组织策略、数据和权限配置。'],
    benchmarks: [],
    userReviews: [
      {
        summary: '用户讨论常把 Copilot 的优势归结为 IDE 内低摩擦使用，同时也会关注新计划和 usage-based billing 的复杂度。',
        sentiment: '中性',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/GithubCopilot/comments/1huccl6/copilot_pro_pricing_whats_the_catch/',
      },
    ],
    sources: [
      { sourceName: 'GitHub Copilot Plans', url: 'https://docs.github.com/en/copilot/get-started/plans' },
      { sourceName: 'GitHub Copilot Pricing', url: 'https://github.com/features/copilot/plans' },
      { sourceName: 'GitHub Blog Billing Update', url: 'https://github.blog/news-insights/company-news/github-copilot-is-moving-to-usage-based-billing/' },
    ],
  },
  {
    id: 'windsurf',
    slug: 'windsurf',
    name: 'Windsurf',
    company: 'Cognition',
    description: 'Cognition 旗下的 AI 开发环境，延续 Windsurf 编辑器体验，聚焦上下文驱动的多文件修改和连续开发。',
    category: 'AI IDE',
    tags: ['编辑器', 'Agent', '工作流'],
    href: '/tools/windsurf',
    officialUrl: 'https://windsurf.com',
    pricing: 'Free / Paid；具体以官网计划为准。',
    bestFor: ['在编辑器里连续修改多文件项目', '基于上下文推进功能迭代', '把 AI 辅助编程融入日常开发', '快速验证前端组件和页面调整'],
    coreAdvantages: ['以编辑器为中心，符合开发者日常工作习惯。', '适合多文件修改和上下文驱动的任务推进。', '可用于快速迭代页面、组件和业务逻辑。'],
    limitations: ['复杂任务仍需要明确边界和人工验证。', '不同模型和额度策略需要以官网为准。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Windsurf Official', url: 'https://windsurf.com' }],
  },
  {
    id: 'lovable',
    slug: 'lovable',
    name: 'Lovable',
    company: 'Lovable',
    description: 'Lovable 的 AI 应用生成平台，用自然语言生成全栈原型、页面和产品流程，适合零基础用户快速验证想法。',
    category: 'App Builder',
    tags: ['原型', '应用生成', '低门槛'],
    href: '/tools/lovable',
    officialUrl: 'https://lovable.dev',
    pricing: 'Free / Paid credits；个人和团队按计划与 credits 使用。',
    bestFor: ['从自然语言生成产品原型', '非技术用户验证页面和业务想法', '搭建 MVP、内部工具和简单 Web 应用', '结合 Supabase、GitHub 等工作流继续迭代'],
    coreAdvantages: ['官方定位为 full-stack AI development platform，可生成真实代码。', '适合零基础用户用自然语言快速得到可运行原型。', '对 landing page、MVP 和内部工具的第一版验证很快。', '支持与常见开发和部署工作流连接。'],
    limitations: ['复杂应用仍需要开发者接手架构、权限和后端细节。', '多轮修改可能消耗较多 credits。', '生成结果需要人工检查安全、数据和边界状态。'],
    benchmarks: [],
    userReviews: [
      {
        summary: 'Product Hunt 反馈普遍认可它能快速把提示词变成原型和 MVP，但也提到复杂应用和成本控制需要注意。',
        sentiment: '中性',
        sourceName: 'Product Hunt',
        url: 'https://www.producthunt.com/products/lovable',
      },
      {
        summary: 'Reddit 用户反馈显示，非技术用户能做出可用产品，但 credits 和升级方式容易引发困惑。',
        sentiment: '中性',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/lovable/comments/1p4movq/lovables_pricing_model_is_all_over_the_place/',
      },
    ],
    sources: [
      { sourceName: 'Lovable Docs', url: 'https://docs.lovable.dev/introduction/welcome' },
      { sourceName: 'Lovable Pricing', url: 'https://lovable.dev/pricing' },
      { sourceName: 'Business Insider Lovable User Report', url: 'https://www.businessinsider.com/lovable-arr-hit-500-million-surprising-facts-about-its-users-2026-6' },
    ],
  },
  {
    id: 'bolt',
    slug: 'bolt',
    name: 'Bolt',
    company: 'StackBlitz',
    description: 'StackBlitz 的浏览器原型工具，可从提示词生成、运行和部署 Web 应用，亮点是无需本地环境即可看到结果。',
    category: 'App Builder',
    tags: ['浏览器', '原型', '快速启动'],
    href: '/tools/bolt',
    officialUrl: 'https://bolt.new',
    pricing: 'Free / Paid token-based；免费额度用完后需要等待或升级。',
    bestFor: ['在浏览器里从提示词启动项目', '快速生成并运行全栈 Web 原型', '边调试边修改前端和后端代码', '把想法转成可演示版本'],
    coreAdvantages: ['无需离开浏览器即可 prompt、运行、编辑和部署应用。', '适合快速看到可运行结果，降低环境配置成本。', '支持 token-based 计划，适合按使用量扩展。'],
    limitations: ['Token 消耗和成本需要提前关注。', '复杂生产级应用仍需要人工架构和测试。', '公开评价中也有用户反馈稳定性和支持体验不一致。'],
    benchmarks: [],
    userReviews: [
      {
        summary: 'Product Hunt 页面强调它能在浏览器内生成、运行、调试并部署全栈应用。',
        sentiment: '正面',
        sourceName: 'Product Hunt',
        url: 'https://www.producthunt.com/products/bolt-new',
      },
      {
        summary: '部分公开用户反馈认为它适合快速原型，但从零做到生产级应用仍有挑战。',
        sentiment: '中性',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/boltnewbuilders/comments/1jiqb3u/do_you_know_anything_made_with_boltnew/',
      },
    ],
    sources: [
      { sourceName: 'Bolt Official', url: 'https://bolt.new/' },
      { sourceName: 'Bolt Pricing', url: 'https://bolt.new/pricing' },
      { sourceName: 'Bolt Help Center', url: 'https://support.bolt.new/building/intro-bolt' },
      { sourceName: 'Bolt GitHub', url: 'https://github.com/stackblitz/bolt.new' },
    ],
  },
  {
    id: 'v0',
    slug: 'v0',
    name: 'v0',
    company: 'Vercel',
    description: 'Vercel 的 AI UI 生成工具，擅长从文字或截图生成 React、Tailwind 和 Next.js 页面，适合快速表达界面方案。',
    category: 'App Builder',
    tags: ['UI 生成', 'React', '原型'],
    href: '/tools/v0',
    officialUrl: 'https://v0.app',
    pricing: 'Free credits / Paid；Free、Team、Business 等计划包含不同月度 credits。',
    bestFor: ['从提示词或截图生成 UI 原型', '快速生成 React、Tailwind 和 Next.js 页面', '探索 landing page、定价页和后台界面结构', '把原型部署或转成 PR 继续开发'],
    coreAdvantages: ['官方定位为可生成真实代码、全栈应用和 agent 的 AI agent。', '对 UI 结构和页面排版的初稿生成速度快。', '与 Vercel 部署和 GitHub 工作流衔接自然。', '适合设计师和产品经理快速表达页面想法。'],
    limitations: ['复杂后端、权限和数据模型仍需要工程补充。', 'Credits 消耗取决于模型和提示复杂度。', '生成 UI 需要继续做品牌、交互和响应式细节打磨。'],
    benchmarks: [],
    userReviews: [
      {
        summary: 'Product Hunt 反馈认为 v0 适合快速把 rough prompts 或截图转成 React/Tailwind 原型，尤其适合 landing page 和 demo。',
        sentiment: '正面',
        sourceName: 'Product Hunt',
        url: 'https://www.producthunt.com/products/v0',
      },
      {
        summary: 'Reddit 讨论中用户认可新版能力提升，但也会关注 credits 和价格变化。',
        sentiment: '中性',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/vercel/comments/1lw0uyl/whats_everyones_experience_with_v0dev_do_you_hate/',
      },
    ],
    sources: [
      { sourceName: 'v0 Docs', url: 'https://v0.app/docs/' },
      { sourceName: 'v0 Pricing', url: 'https://v0.app/pricing' },
      { sourceName: 'Vercel v0 Pricing Update', url: 'https://vercel.com/blog/updated-v0-pricing' },
    ],
  },
  {
    id: 'replit',
    slug: 'replit',
    name: 'Replit',
    company: 'Replit',
    description: 'Replit 的在线开发与部署平台，结合 Agent 可从想法生成应用，并在浏览器中运行、协作和分享可用版本。',
    category: 'App Builder',
    tags: ['在线 IDE', '运行环境', '分享'],
    href: '/tools/replit',
    officialUrl: 'https://replit.com',
    pricing: 'Free / Paid credits / usage-based Agent；不同计划包含不同月度 credits。',
    bestFor: ['无需配置本地环境快速创建应用', '在线运行、部署和分享项目', '教学、演示和协作调试', '用 Replit Agent 从想法生成初版应用'],
    coreAdvantages: ['浏览器内即可从 idea 到 app，适合零环境启动。', '包含在线 IDE、运行环境、部署和协作能力。', 'Agent 文档覆盖 prompt、构建、发布和计费管理。', '适合教学和快速演示可用版本。'],
    limitations: ['AI Agent 使用为按工作量计费，需要控制预算。', '公开用户反馈中较常见的关注点是成本可预期性。', '复杂项目仍需要本地或专业工程流程接管。'],
    benchmarks: [],
    userReviews: [
      {
        summary: 'Reddit 和社区讨论中，用户认可 Replit Agent 的便利性，但对 AI Agent 计费可预期性有明显担忧。',
        sentiment: '负面',
        sourceName: 'Reddit',
        url: 'https://www.reddit.com/r/replit/comments/1fahuge/buyer_beware_replits_ai_agent_review/',
      },
      {
        summary: 'Trustpilot 汇总显示用户反馈分化，既有在线开发便利性的认可，也有价格和支持体验方面的抱怨。',
        sentiment: '中性',
        sourceName: 'Trustpilot',
        url: 'https://www.trustpilot.com/review/replit.com',
      },
    ],
    sources: [
      { sourceName: 'Replit Docs', url: 'https://docs.replit.com/build/welcome' },
      { sourceName: 'Replit Agent Docs', url: 'https://docs.replit.com/references/agent/overview' },
      { sourceName: 'Replit Pricing', url: 'https://replit.com/pricing' },
      { sourceName: 'Replit AI Billing Docs', url: 'https://docs.replit.com/billing/ai-billing' },
    ],
  },
  {
    id: 'trae',
    slug: 'trae',
    name: 'Trae',
    company: 'ByteDance',
    description: '字节跳动推出的 AI IDE，面向本地开发中的代码理解、文件修改和智能补全，对中文用户和日常迭代更友好。',
    category: 'AI IDE',
    tags: ['本地开发', '上下文', '辅助编码'],
    href: '/tools/trae',
    officialUrl: 'https://trae.ai',
    pricing: '以官网为准。',
    bestFor: ['中文开发者的本地 AI 编程辅助', '理解项目上下文和修改文件', '日常组件、样式和功能迭代'],
    coreAdvantages: ['更贴近中文用户使用习惯。', '适合本地开发中的上下文理解和文件修改。', '可用于快速解释代码和辅助完成常规开发任务。'],
    limitations: ['公开第三方评测资料相对有限。', '具体模型、额度和价格策略需要以官网为准。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Trae Official', url: 'https://trae.ai' }],
  },
  {
    id: 'cline',
    slug: 'cline',
    name: 'Cline',
    company: 'Cline',
    description: 'Cline 团队维护的开源 VS Code Agent，可连接不同模型执行文件修改和命令，优势是透明、可配置、可控。',
    category: 'Open Source',
    tags: ['开源', 'VS Code', 'Agent'],
    href: '/tools/cline',
    officialUrl: 'https://cline.bot',
    pricing: 'Open source；模型费用取决于你连接的模型服务。',
    bestFor: ['在 VS Code 中使用开源 Agent', '连接自选模型完成文件修改', '需要更强可控性和可配置性的工作流'],
    coreAdvantages: ['开源和可配置，适合自定义开发环境。', '能在编辑器中执行文件修改和命令。', '适合连接不同模型，按团队偏好配置。'],
    limitations: ['需要理解模型 key、权限和命令执行边界。', '体验质量取决于所接入模型和配置。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Cline Official', url: 'https://cline.bot' }],
  },
  {
    id: 'continue',
    slug: 'continue',
    name: 'Continue',
    company: 'Continue',
    description: 'Continue 的开源代码助手平台，可连接多种模型和 IDE，适合团队搭建可控、可扩展的 AI 编程工作流。',
    category: 'Open Source',
    tags: ['开源', '代码助手', '可配置'],
    href: '/tools/continue',
    officialUrl: 'https://continue.dev',
    pricing: 'Open source；模型和托管成本取决于你的配置。',
    bestFor: ['搭建团队可控的 AI 代码助手', '连接不同模型和 IDE', '把 AI 编程能力纳入内部开发环境'],
    coreAdvantages: ['开源、可扩展，适合团队定制。', '支持连接不同模型，便于控制成本和数据流。', '适合需要私有化或灵活配置的团队。'],
    limitations: ['需要配置和维护成本。', '最终体验依赖模型选择和团队工作流设计。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Continue Official', url: 'https://continue.dev' }],
  },
  {
    id: 'deepseek',
    slug: 'deepseek',
    name: 'DeepSeek',
    company: 'DeepSeek',
    description: 'DeepSeek 的国产大模型产品，擅长中文技术问答、代码理解和逻辑推理，可作为 AI 编程流程的模型底座。',
    category: 'Model Platform',
    tags: ['国产模型', '代码推理', '中文'],
    href: '/tools/deepseek',
    officialUrl: 'https://www.deepseek.com',
    pricing: '以官网/API 价格为准。',
    bestFor: ['中文技术问答和代码解释', '作为 AI 编程工具的模型底座', '需求分析、方案梳理和推理任务'],
    coreAdvantages: ['中文理解和推理能力较强。', '适合辅助需求分析和代码解释。', '可作为多种 AI 编程工作流中的底层模型选择。'],
    limitations: ['它本身是模型平台，不等同于完整 IDE 或 Agent。', '需要配合开发工具或 API 集成使用。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'DeepSeek Official', url: 'https://www.deepseek.com' }],
  },
  {
    id: 'qwen',
    slug: 'qwen',
    name: 'Qwen',
    company: 'Alibaba Cloud',
    description: '阿里云的通义千问模型系列，覆盖多语言生成、代码辅助和工具调用，适合接入产品原型与开发工作流。',
    category: 'Model Platform',
    tags: ['国产模型', '多语言', '工具调用'],
    href: '/tools/qwen',
    officialUrl: 'https://qwen.ai',
    pricing: '以官网/API 价格为准。',
    bestFor: ['多语言代码生成和中文问答', '工具调用和应用集成', '作为产品原型助手的模型底座'],
    coreAdvantages: ['模型生态丰富，便于接入不同应用场景。', '适合中文和多语言任务。', '可用于工具调用、代码生成和产品辅助流程。'],
    limitations: ['需要结合具体产品或开发工具使用。', '不同模型版本能力和成本差异较大。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Qwen Official', url: 'https://qwen.ai' }],
  },
  {
    id: 'kimi',
    slug: 'kimi',
    name: 'Kimi',
    company: 'Moonshot AI',
    description: '月之暗面的 AI 助手，主打长文本理解和资料分析，适合需求梳理、文档总结和编码前的提示词准备。',
    category: 'Model Platform',
    tags: ['国产模型', '长上下文', '需求分析'],
    href: '/tools/kimi',
    officialUrl: 'https://www.kimi.com/',
    pricing: '以官网/API 价格为准。',
    bestFor: ['长文档理解和需求梳理', '项目资料总结和前期调研', '辅助生成提示词和产品说明'],
    coreAdvantages: ['适合长上下文资料处理。', '对中文产品资料、需求文档和总结任务友好。', '可作为编码前的信息整理工具。'],
    limitations: ['不是专门的代码编辑器或 Agent。', '复杂代码修改仍需要搭配开发工具。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'Kimi Official', url: 'https://kimi.moonshot.cn' }],
  },
  {
    id: 'doubao',
    slug: 'doubao',
    name: '豆包',
    company: 'ByteDance',
    description: '字节跳动的 AI 助手，覆盖中文问答、内容生成、产品文案和轻量代码解释，适合日常协作与想法整理。',
    category: 'Model Platform',
    tags: ['国产模型', '中文', '文案'],
    href: '/tools/doubao',
    officialUrl: 'https://www.doubao.com',
    pricing: '以官网/API 价格为准。',
    bestFor: ['中文内容生成和产品文案', '轻量代码解释和技术问答', '日常想法整理和方案草拟'],
    coreAdvantages: ['中文使用体验友好。', '适合内容、文案和轻量问答场景。', '覆盖日常 AI 协作中的多种任务。'],
    limitations: ['不是完整 AI 编程 IDE。', '复杂工程任务需要结合专业开发工具。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: '豆包 Official', url: 'https://www.doubao.com' }],
  },
  {
    id: 'zhipu',
    slug: 'zhipu',
    name: '智谱 GLM',
    company: '智谱 AI',
    description: '智谱 AI 的 GLM 模型与产品体系，面向中文问答、知识处理和应用开发集成，适合企业和产品场景接入。',
    category: 'Model Platform',
    tags: ['国产模型', 'GLM', '应用集成'],
    href: '/tools/zhipu',
    officialUrl: 'https://www.bigmodel.cn',
    pricing: '以官网/API 价格为准。',
    bestFor: ['中文问答和知识处理', '应用开发中的模型集成', '企业场景的 AI 能力组合'],
    coreAdvantages: ['提供面向应用开发的模型平台能力。', '适合中文知识问答和集成场景。', '便于作为产品功能中的模型服务。'],
    limitations: ['需要开发集成，不能直接替代 IDE。', '具体能力取决于所选模型版本和配置。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: 'BigModel Official', url: 'https://www.bigmodel.cn' }],
  },
  {
    id: 'wenxin',
    slug: 'wenxin',
    name: '文心一言',
    company: 'Baidu',
    description: '百度的文心一言 AI 助手，面向中文问答、内容生成和企业应用场景，可辅助方案整理与产品文案打磨。',
    category: 'Model Platform',
    tags: ['国产模型', '中文', '企业应用'],
    href: '/tools/wenxin',
    officialUrl: 'https://yiyan.baidu.com',
    pricing: '以官网/API 价格为准。',
    bestFor: ['中文问答和内容生成', '需求表达和方案整理', '企业场景中的 AI 辅助能力'],
    coreAdvantages: ['中文内容生成和问答体验友好。', '适合产品文案、方案整理和知识辅助。', '可结合百度生态进行应用集成。'],
    limitations: ['不是专门面向代码库的 Agent。', '复杂开发任务仍需要搭配开发环境。'],
    benchmarks: [],
    userReviews: [],
    sources: [{ sourceName: '文心一言 Official', url: 'https://yiyan.baidu.com' }],
  },
];

export const caseToolFilters = ['全部工具', ...tools.map((tool) => tool.name), '其他'];

export const footerGroups = [
  {
    title: '探索',
    links: [
      { label: '精选案例', href: '/cases' },
      { label: '最新作品', href: '/cases' },
      { label: '学习路径', href: '/learn' },
    ],
  },
  {
    title: '分类',
    links: [
      { label: '数据看板', href: '/cases' },
      { label: '官网', href: '/cases' },
      { label: '原型', href: '/learn' },
    ],
  },
  {
    title: '工具',
    links: [
      { label: 'Codex', href: '/tools' },
      { label: 'Cursor', href: '/tools' },
      { label: 'v0', href: '/tools' },
    ],
  },
  {
    title: '站点',
    links: [
      { label: '关于', href: '/about' },
      { label: '提交作品', href: '/submit' },
      { label: '隐私协议', href: '/privacy' },
    ],
  },
];
